import * as stylex from '@stylexjs/stylex'

import { layerIndexes } from '../../tokens/layers.stylex'
import {
  borderColors,
  ghostElementColors,
  spatial,
  surfaceColors,
  textColors,
} from '../../tokens/semantics.stylex'
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  lineHeights,
  shadows,
  spacing,
} from '../../tokens/value.stylex'

export const datePickerStyles = stylex.create({
  trigger: {
    borderColor: borderColors.default,
    borderRadius: borderRadii.xs,
    borderStyle: 'solid',
    borderWidth: 1,
    overflow: 'hidden',
    paddingInline: spacing.xs,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: {
      default: surfaceColors.default,
      ':hover': ghostElementColors.hover,
      ':active': ghostElementColors.pressed,
    },
    color: textColors.default,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.ui,
    textAlign: 'center',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    height: spatial['control-height-l'],
    minWidth: 0,
    width: '100%',
  },
  triggerGrouped: {
    borderRadius: 0,
    borderWidth: 0,
    flexBasis: '0%',
    flexGrow: 1,
    flexShrink: 1,
    outlineWidth: 0,
    height: '100%',
  },
  triggerOpen: { backgroundColor: ghostElementColors.selected },
  triggerClosed: {},
  triggerDisabled: {
    backgroundColor: surfaceColors.default,
    color: textColors.disabled,
    cursor: 'not-allowed',
  },
  positioner: {
    outline: 'none',
    display: 'flex',
    flexDirection: 'column',
    pointerEvents: 'none',
    zIndex: layerIndexes.popup,
    minHeight: spatial['viewport-height-l'],
  },
  positionerOpen: {},
  positionerClosed: {},
  positionerAnchorHidden: {},
  positionerInstant: {},
  positionerSideTop: { justifyContent: 'flex-end' },
  positionerSideBottom: { justifyContent: 'flex-start' },
  positionerSideLeft: {},
  positionerSideRight: {},
  positionerSideInlineStart: {},
  positionerSideInlineEnd: {},
  positionerAlignStart: {},
  positionerAlignCenter: {},
  positionerAlignEnd: {},
  popup: {
    padding: spacing.s,
    borderColor: borderColors.default,
    borderRadius: borderRadii.xs,
    borderStyle: 'solid',
    borderWidth: 1,
    outline: 'none',
    backgroundColor: surfaceColors.raised,
    boxShadow: shadows.medium,
    color: textColors.default,
    display: 'flex',
    flexDirection: 'column',
    pointerEvents: 'auto',
    transformOrigin: 'var(--transform-origin)',
    maxHeight: 'var(--available-height)',
    maxWidth: 'var(--available-width)',
    width: spatial['multi-select-width-s'],
  },
  inlinePanel: {
    padding: spacing.s,
    alignSelf: 'center',
    color: textColors.default,
    width: spatial['multi-select-width-s'],
  },
  loading: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    minHeight: spatial['viewport-height-l'],
  },
  popupOpen: {},
  popupClosed: {},
  popupStarting: { opacity: 0, transform: 'scale(0.98)' },
  popupEnding: { opacity: 0, transform: 'scale(0.98)' },
  popupInstant: {},
  popupSideTop: {},
  popupSideBottom: {},
  popupSideLeft: {},
  popupSideRight: {},
  popupSideInlineStart: {},
  popupSideInlineEnd: {},
  popupAlignStart: {},
  popupAlignCenter: {},
  popupAlignEnd: {},
  controls: {
    gap: spacing.s,
    display: 'flex',
    flexDirection: 'column',
    paddingTop: spacing.m,
  },
  timeRow: { gap: spacing.s, alignItems: 'flex-end', display: 'flex' },
  controlLabel: {
    color: textColors.muted,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    lineHeight: lineHeights.compact,
  },
  field: {
    gap: spacing.xs,
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  input: { textAlign: 'center' },
  setNowAction: { flexShrink: 0 },
  applyAction: { width: '100%' },
})
