import * as stylex from "@stylexjs/stylex";

import {
  borderColors,
  elementColors,
  focusColors,
  spatial,
  textColors,
} from "../../tokens/semantics.stylex";
import { borderRadii, fontFamilies, fontSizes, lineHeights, spacing } from "../../tokens/value.stylex";

const reducedMotion = "@media (prefers-reduced-motion: reduce)";

const blinkCaret = stylex.keyframes({
  "0%": { opacity: 1 },
  "49%": { opacity: 1 },
  "50%": { opacity: 0 },
  "100%": { opacity: 0 },
});

export const dataGridFilterClauseStyles = stylex.create({
  list: {
    gap: spacing.xs,
    alignItems: "center",
    cursor: "text",
    display: "flex",
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    outlineColor: focusColors.ring,
    outlineOffset: `calc(-1 * ${spatial["focus-ring-width"]})`,
    outlineStyle: "solid",
    outlineWidth: { default: 0, ":focus-visible": spatial["focus-ring-width"] },
    minWidth: 0,
    overflowX: "auto",
    overflowY: "hidden",
    overscrollBehaviorX: "none",
    "::after": {
      animationDuration: "1s",
      animationIterationCount: "infinite",
      animationName: { default: "none", [reducedMotion]: "none", ":focus": blinkCaret },
      animationTimingFunction: "steps(1, end)",
      backgroundColor: textColors.default,
      content: "",
      display: "block",
      flexShrink: 0,
      opacity: { default: 0, ":focus": 1 },
      pointerEvents: "none",
      height: spatial["icon-size-s"],
      width: 1,
    },
  },
  root: {
    borderRadius: borderRadii.xs,
    gap: spacing.xs,
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    outlineColor: focusColors.ringDanger,
    outlineOffset: `calc(-1 * ${spatial["focus-ring-width"]})`,
    outlineStyle: "solid",
    outlineWidth: { default: 0, ":focus": spatial["focus-ring-width"] },
    minWidth: 0,
  },
  controls: {
    borderColor: borderColors.default,
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
    alignItems: "center",
    backgroundColor: elementColors.default,
    display: "inline-flex",
    height: spatial["control-height-s"],
    maxWidth: spatial["grid-track-m"],
    minWidth: 0,
  },
  controlsInvalid: { borderColor: borderColors.danger },
  trigger: {
    borderRadius: 0,
    borderStyle: "none",
    gap: spacing.s,
    alignItems: "center",
    appearance: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": elementColors.hover,
      ":active": elementColors.pressed,
    },
    color: textColors.default,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    lineHeight: lineHeights.compact,
    outlineColor: focusColors.ring,
    outlineOffset: `calc(-1 * ${spatial["focus-ring-width"]})`,
    outlineStyle: "solid",
    outlineWidth: { default: 0, ":focus-visible": spatial["focus-ring-width"] },
    height: "100%",
    minWidth: 0,
    paddingLeft: spacing.xs,
    paddingRight: spacing.xxs,
  },
  triggerDisabled: {
    backgroundColor: elementColors.disabled,
    color: textColors.disabled,
    cursor: "not-allowed",
  },
  triggerInvalid: { borderColor: borderColors.danger, color: textColors.danger },
  remove: {
    borderRadius: 0,
    flexShrink: 0,
    outlineOffset: `calc(-1 * ${spatial["focus-ring-width"]})`,
    height: "100%",
    width: spatial["control-height-s"],
  },
  column: { overflow: "hidden", flexShrink: 0, textOverflow: "ellipsis", whiteSpace: "nowrap" },
  operator: { flexShrink: 0 },
  value: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  invalidDescription: {
    gap: spacing.xxs,
    alignItems: "center",
    color: textColors.danger,
    display: "inline-flex",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    lineHeight: lineHeights.compact,
    whiteSpace: "nowrap",
  },
});
