/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9b5d18ebccd43e6f7b5340fb9a5c3fd2)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/productWorker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
