import * as stylex from '@stylexjs/stylex'

import {
  borderColors,
  focusColors,
  spatial,
  surfaceColors,
  textColors,
} from '../../tokens/semantics.stylex'
import {
  dimensions,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from '../../tokens/value.stylex'
import { swimlaneTimelineColors } from './swimlaneTimelineColors.stylex'

export const swimlaneTimelineStyles = stylex.create({
  scrollSurface: {
    minWidth: '100%',
  },
  table: {
    borderCollapse: 'separate',
    borderSpacing: 0,
    boxSizing: 'border-box',
    color: textColors.default,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    lineHeight: lineHeights.compact,
    tableLayout: 'fixed',
    width: '100%',
  },
  labelColumn: {
    width: spatial['grid-track-m'],
  },
  snapshotColumn: {
    width: dimensions[100],
  },
  header: {
    position: 'sticky',
    zIndex: 2,
    top: 0,
  },
  headerCell: {
    overflow: 'hidden',
    paddingInline: spacing.s,
    backgroundColor: surfaceColors.background,
    borderBlockEndColor: borderColors.default,
    borderBlockEndStyle: 'solid',
    borderBlockEndWidth: 1,
    color: textColors.muted,
    fontFamily: fontFamilies.mono,
    fontWeight: fontWeights.regular,
    textAlign: 'center',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    height: spatial['collection-row-height-xl'],
  },
  labelHeaderCell: {
    insetInlineStart: 0,
    position: 'sticky',
    textAlign: 'start',
    zIndex: 2,
  },
  laneHeadingRow: {
    backgroundColor: surfaceColors.subtle,
  },
  laneHeadingCell: {
    padding: 0,
    backgroundColor: 'transparent',
    borderBlockEndColor: borderColors.default,
    borderBlockEndStyle: 'solid',
    borderBlockEndWidth: 1,
    insetInlineStart: 0,
    position: 'sticky',
    textAlign: 'start',
    zIndex: 1,
    height: spatial['collection-row-height-xl'],
  },
  laneHeadingContinuationCell: {
    padding: 0,
    backgroundColor: 'transparent',
    borderBlockEndColor: borderColors.default,
    borderBlockEndStyle: 'solid',
    borderBlockEndWidth: 1,
  },
  laneTrigger: {
    borderWidth: 0,
    gap: spacing.xs,
    paddingInline: spacing.s,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: 'transparent',
    color: textColors.muted,
    cursor: 'pointer',
    display: 'flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.regular,
    justifyContent: 'space-between',
    lineHeight: lineHeights.ui,
    outlineColor: focusColors.ring,
    outlineOffset: -2,
    outlineStyle: {
      default: 'none',
      ':focus-visible': 'solid',
    },
    outlineWidth: spatial['focus-ring-width'],
    textAlign: 'start',
    height: '100%',
    width: spatial['grid-track-m'],
  },
  laneTriggerLeading: {
    gap: spacing.xs,
    alignItems: 'center',
    display: 'flex',
    minWidth: 0,
  },
  laneIndicator: {
    display: 'block',
    flexShrink: 0,
    height: spatial['icon-size-s'],
    width: spatial['icon-size-s'],
  },
  laneIndicatorExpanded: {
    transform: 'rotate(90deg)',
  },
  laneLabel: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  laneSuffix: {
    flexShrink: 0,
    fontVariantNumeric: 'tabular-nums',
  },
  bodyCell: {
    borderInlineEndColor: borderColors.default,
    borderInlineEndStyle: 'solid',
    borderInlineEndWidth: { default: 1, ':last-child': 0 },
    boxSizing: 'border-box',
  },
  trackLabel: {
    overflow: 'hidden',
    paddingInline: spacing.s,
    backgroundColor: surfaceColors.background,
    borderBlockEndColor: borderColors.default,
    borderBlockEndStyle: 'solid',
    borderBlockEndWidth: 1,
    color: textColors.muted,
    fontFamily: fontFamilies.mono,
    fontWeight: fontWeights.regular,
    insetInlineStart: 0,
    position: 'sticky',
    textAlign: 'start',
    zIndex: 1,
    height: spatial['collection-row-height-l'],
  },
  cell: {
    padding: 0,
    backgroundColor: surfaceColors.background,
    borderBlockEndColor: borderColors.default,
    borderBlockEndStyle: 'solid',
    borderBlockEndWidth: 1,
    color: textColors.disabled,
    textAlign: 'center',
    height: spatial['collection-row-height-s'],
  },
  cellActive: {
    color: swimlaneTimelineColors.activityIndicator,
  },
  cellAction: {
    padding: 0,
    borderWidth: 0,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: 'transparent',
    color: 'currentColor',
    cursor: 'pointer',
    display: 'flex',
    outlineColor: focusColors.ring,
    outlineOffset: -2,
    outlineStyle: {
      default: 'none',
      ':focus-visible': 'solid',
    },
    outlineWidth: spatial['focus-ring-width'],
    height: '100%',
    width: '100%',
  },
  statusMarker: {
    backgroundColor: 'currentColor',
    display: 'block',
    height: spatial['icon-size-xs'],
    width: '100%',
  },
})
