import * as stylex from "@stylexjs/stylex";

import { layerIndexes } from "../../tokens/layers.stylex";
import {
  backgroundColors,
  borderColors,
  spatial,
  textColors,
} from "../../tokens/semantics.stylex";
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  shadows,
  spacing,
} from "../../tokens/value.stylex";
import { multiSelectVars } from "./multiSelectVars.stylex";

export const multiSelectStyles = stylex.create({
  triggerOpen: {},
  triggerPressed: {},
  triggerDisabled: {},
  positioner: { outline: "none", zIndex: layerIndexes.popup },
  positionerOpen: {},
  positionerClosed: {},
  positionerAnchorHidden: {},
  positionerInstant: {},
  positionerSideTop: {},
  positionerSideBottom: {},
  positionerSideLeft: {},
  positionerSideRight: {},
  positionerSideInlineStart: {},
  positionerSideInlineEnd: {},
  positionerAlignStart: {},
  positionerAlignCenter: {},
  positionerAlignEnd: {},
  popup: {
    borderColor: borderColors.border,
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    outline: "none",
    backgroundColor: backgroundColors["bg-popover"],
    boxShadow: shadows.medium,
    color: textColors["text-default"],
    transformOrigin: "var(--transform-origin)",
    maxWidth: "var(--available-width)",
  },
  popupOpen: {},
  popupClosed: {},
  popupStarting: {},
  popupEnding: {},
  popupInstant: {},
  popupSideTop: {},
  popupSideBottom: {},
  popupSideLeft: {},
  popupSideRight: {},
  popupSideInlineStart: {},
  popupSideInlineEnd: {},
  popupAlignStart: {},
  popupAlignCenter: {},
  popupAlignEnd: {},
  popupWidthS: { width: spatial["multi-select-width-s"] },
  popupWidthM: { width: spatial["multi-select-width-m"] },
  popupWidthL: { width: spatial["multi-select-width-l"] },
  section: {
    padding: spatial["popup-collection-padding"],
  },
  separator: {
    marginBlock: spatial["popup-collection-padding"],
    backgroundColor: borderColors["border-secondary"],
    height: 1,
  },
  options: {
    padding: spatial["popup-collection-padding"],
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflowY: "auto",
  },
  optionsHeightS: { maxHeight: spatial["viewport-height-s"] },
  optionsHeightM: { maxHeight: spatial["viewport-height-m"] },
  optionsHeightL: { maxHeight: spatial["viewport-height-l"] },
  row: {
    [multiSelectVars.actionOpacity]: {
      default: 0,
      ":focus-within": 1,
      ":hover": 1,
    },
    [multiSelectVars.actionVisibility]: {
      default: "hidden",
      ":focus-within": "visible",
      ":hover": "visible",
    },
    borderRadius: borderRadii.xs,
    gap: spacing.s,
    paddingInline: spatial["popup-item-inline-padding"],
    alignItems: "center",
    boxSizing: "border-box",
    display: "grid",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.regular,
    gridTemplateColumns: `${spatial["icon-size-s"]} minmax(0, 1fr)`,
    lineHeight: lineHeights.ui,
    userSelect: "none",
    minHeight: spatial["popup-row-min-height"],
  },
  rowDisabled: { color: textColors["text-disabled"] },
  optionButton: {
    padding: 0,
    borderWidth: 0,
    overflow: "hidden",
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    color: "inherit",
    cursor: "pointer",
    display: "flex",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.ui,
    outlineColor: borderColors["outline"],
    outlineOffset: -1,
    outlineStyle: "solid",
    outlineWidth: { default: 0, ":focus-visible": spatial["focus-ring-width"] },
    userSelect: "none",
    minWidth: 0,
    width: "100%",
  },
  optionButtonDisabled: { cursor: "not-allowed" },
  optionText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  action: {
    color: textColors["text-muted"],
    flexShrink: 0,
    marginInlineStart: "auto",
    opacity: multiSelectVars.actionOpacity,
    visibility: multiSelectVars.actionVisibility,
  },
  empty: {
    padding: spacing.l,
    color: textColors["text-muted"],
    display: "block",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.ui,
  },
});
