import * as stylex from "@stylexjs/stylex";

import { layerIndexes } from "../../tokens/layers.stylex";
import {
  backgroundColors,
  borderColors,
  spatial,
  textColors,
} from "../../tokens/semantics.stylex";
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  lineHeights,
  shadows,
  spacing,
} from "../../tokens/value.stylex";
import { multiSelectVars } from "./multiSelectVars.stylex";

export const multiSelectStyles = stylex.create({
  positioner: { outline: "none", zIndex: layerIndexes.popup },
  popup: {
    borderColor: borderColors.border,
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    outline: "none",
    backgroundColor: backgroundColors["bg-popover"],
    boxShadow: shadows.medium,
    color: textColors["text-default"],
    transformOrigin: "var(--transform-origin)",
    maxWidth: "var(--available-width)",
  },
  popupWidthS: { width: 240 },
  popupWidthM: { width: 280 },
  popupWidthL: { width: 360 },
  header: { padding: spacing.xs },
  separator: { backgroundColor: borderColors["border-secondary"], height: 1 },
  options: {
    padding: spacing.xxs,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflowY: "auto",
  },
  optionsHeightS: { maxHeight: 160 },
  optionsHeightM: { maxHeight: 240 },
  optionsHeightL: { maxHeight: 320 },
  row: {
    [multiSelectVars.actionOpacity]: {
      default: 0,
      ":focus-within": 1,
      ":hover": 1,
    },
    [multiSelectVars.actionVisibility]: {
      default: "hidden",
      ":focus-within": "visible",
      ":hover": "visible",
    },
    borderRadius: borderRadii.xs,
    gap: spacing.s,
    paddingInline: spacing.s,
    alignItems: "center",
    display: "grid",
    gridTemplateColumns: "14px minmax(0, 1fr)",
    userSelect: "none",
    minHeight: 28,
  },
  rowDisabled: { color: textColors["text-disabled"] },
  optionButton: {
    padding: 0,
    borderWidth: 0,
    overflow: "hidden",
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    color: "inherit",
    cursor: "pointer",
    display: "flex",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.none,
    outlineColor: borderColors["border-focused"],
    outlineOffset: -1,
    outlineStyle: "solid",
    outlineWidth: { default: 0, ":focus-visible": spatial["focus-ring-width"] },
    userSelect: "none",
    minWidth: 0,
    width: "100%",
  },
  optionButtonDisabled: { cursor: "not-allowed" },
  optionText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  action: {
    color: textColors["text-muted"],
    flexShrink: 0,
    marginInlineStart: "auto",
    opacity: multiSelectVars.actionOpacity,
    visibility: multiSelectVars.actionVisibility,
  },
  empty: {
    padding: spacing.l,
    color: textColors["text-muted"],
    display: "block",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.normal,
  },
});
