export const codeEditorPropNames = [
  'value',
  'onValueChange',
  'accessibilityLabel',
  'id',
  'labelledBy',
  'describedBy',
  'readOnly',
  'disabled',
  'invalid',
  'expanded',
  'defaultExpanded',
  'onExpandedChange',
  'layout',
  'focusOnMount',
] as const
