/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoundationsTypographyRouteImport } from './routes/foundations/typography'
import { Route as FoundationsColorsRouteImport } from './routes/foundations/colors'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsTypographyRoute = FoundationsTypographyRouteImport.update({
  id: '/foundations/typography',
  path: '/foundations/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsColorsRoute = FoundationsColorsRouteImport.update({
  id: '/foundations/colors',
  path: '/foundations/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/button': typeof ComponentsButtonRoute
  '/foundations/colors': typeof FoundationsColorsRoute
  '/foundations/typography': typeof FoundationsTypographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/button': typeof ComponentsButtonRoute
  '/foundations/colors': typeof FoundationsColorsRoute
  '/foundations/typography': typeof FoundationsTypographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/button': typeof ComponentsButtonRoute
  '/foundations/colors': typeof FoundationsColorsRoute
  '/foundations/typography': typeof FoundationsTypographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/button'
    | '/foundations/colors'
    | '/foundations/typography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/button'
    | '/foundations/colors'
    | '/foundations/typography'
  id:
    | '__root__'
    | '/'
    | '/components/button'
    | '/foundations/colors'
    | '/foundations/typography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  FoundationsColorsRoute: typeof FoundationsColorsRoute
  FoundationsTypographyRoute: typeof FoundationsTypographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/typography': {
      id: '/foundations/typography'
      path: '/foundations/typography'
      fullPath: '/foundations/typography'
      preLoaderRoute: typeof FoundationsTypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/colors': {
      id: '/foundations/colors'
      path: '/foundations/colors'
      fullPath: '/foundations/colors'
      preLoaderRoute: typeof FoundationsColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  FoundationsColorsRoute: FoundationsColorsRoute,
  FoundationsTypographyRoute: FoundationsTypographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
