/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsAccordionRouteImport } from './routes/components/accordion'
import { Route as ComponentsActionListRouteImport } from './routes/components/action-list'
import { Route as ComponentsBinaryValueRouteImport } from './routes/components/binary-value'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsButtonGroupRouteImport } from './routes/components/button-group'
import { Route as ComponentsButtonLinkRouteImport } from './routes/components/button-link'
import { Route as ComponentsCheckboxRouteImport } from './routes/components/checkbox'
import { Route as ComponentsCodeEditorRouteImport } from './routes/components/code-editor'
import { Route as ComponentsComboboxRouteImport } from './routes/components/combobox'
import { Route as ComponentsContextMenuRouteImport } from './routes/components/context-menu'
import { Route as ComponentsContextSwitcherRouteImport } from './routes/components/context-switcher'
import { Route as ComponentsCopyButtonRouteImport } from './routes/components/copy-button'
import { Route as ComponentsDataTableRouteImport } from './routes/components/data-table'
import { Route as ComponentsFieldRouteImport } from './routes/components/field'
import { Route as ComponentsFieldsetRouteImport } from './routes/components/fieldset'
import { Route as ComponentsInputRouteImport } from './routes/components/input'
import { Route as ComponentsInputGroupRouteImport } from './routes/components/input-group'
import { Route as ComponentsJsonViewRouteImport } from './routes/components/json-view'
import { Route as ComponentsKeyboardInputRouteImport } from './routes/components/keyboard-input'
import { Route as ComponentsMenuRouteImport } from './routes/components/menu'
import { Route as ComponentsRelationValueRouteImport } from './routes/components/relation-value'
import { Route as ComponentsResizablePanelRouteImport } from './routes/components/resizable-panel'
import { Route as ComponentsSearchRouteImport } from './routes/components/search'
import { Route as ComponentsSegmentedControlRouteImport } from './routes/components/segmented-control'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as ComponentsSidePanelRouteImport } from './routes/components/side-panel'
import { Route as ComponentsSpinnerRouteImport } from './routes/components/spinner'
import { Route as ComponentsStructuredValuePreviewRouteImport } from './routes/components/structured-value-preview'
import { Route as ComponentsSwitchRouteImport } from './routes/components/switch'
import { Route as ComponentsTabViewRouteImport } from './routes/components/tab-view'
import { Route as ComponentsTextFieldRouteImport } from './routes/components/text-field'
import { Route as ComponentsTextLinkRouteImport } from './routes/components/text-link'
import { Route as ComponentsTextareaRouteImport } from './routes/components/textarea'
import { Route as ComponentsTimestampValueRouteImport } from './routes/components/timestamp-value'
import { Route as ComponentsToastRouteImport } from './routes/components/toast'
import { Route as ComponentsToggleGroupRouteImport } from './routes/components/toggle-group'
import { Route as ComponentsTooltipRouteImport } from './routes/components/tooltip'
import { Route as FoundationsColorsRouteImport } from './routes/foundations/colors'
import { Route as FoundationsTypographyRouteImport } from './routes/foundations/typography'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAccordionRoute = ComponentsAccordionRouteImport.update({
  id: '/components/accordion',
  path: '/components/accordion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsActionListRoute = ComponentsActionListRouteImport.update({
  id: '/components/action-list',
  path: '/components/action-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBinaryValueRoute = ComponentsBinaryValueRouteImport.update({
  id: '/components/binary-value',
  path: '/components/binary-value',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonGroupRoute = ComponentsButtonGroupRouteImport.update({
  id: '/components/button-group',
  path: '/components/button-group',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonLinkRoute = ComponentsButtonLinkRouteImport.update({
  id: '/components/button-link',
  path: '/components/button-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCheckboxRoute = ComponentsCheckboxRouteImport.update({
  id: '/components/checkbox',
  path: '/components/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCodeEditorRoute = ComponentsCodeEditorRouteImport.update({
  id: '/components/code-editor',
  path: '/components/code-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsComboboxRoute = ComponentsComboboxRouteImport.update({
  id: '/components/combobox',
  path: '/components/combobox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsContextMenuRoute = ComponentsContextMenuRouteImport.update({
  id: '/components/context-menu',
  path: '/components/context-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsContextSwitcherRoute =
  ComponentsContextSwitcherRouteImport.update({
    id: '/components/context-switcher',
    path: '/components/context-switcher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsCopyButtonRoute = ComponentsCopyButtonRouteImport.update({
  id: '/components/copy-button',
  path: '/components/copy-button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDataTableRoute = ComponentsDataTableRouteImport.update({
  id: '/components/data-table',
  path: '/components/data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFieldRoute = ComponentsFieldRouteImport.update({
  id: '/components/field',
  path: '/components/field',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFieldsetRoute = ComponentsFieldsetRouteImport.update({
  id: '/components/fieldset',
  path: '/components/fieldset',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsInputRoute = ComponentsInputRouteImport.update({
  id: '/components/input',
  path: '/components/input',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsInputGroupRoute = ComponentsInputGroupRouteImport.update({
  id: '/components/input-group',
  path: '/components/input-group',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsJsonViewRoute = ComponentsJsonViewRouteImport.update({
  id: '/components/json-view',
  path: '/components/json-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsKeyboardInputRoute = ComponentsKeyboardInputRouteImport.update({
  id: '/components/keyboard-input',
  path: '/components/keyboard-input',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsMenuRoute = ComponentsMenuRouteImport.update({
  id: '/components/menu',
  path: '/components/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRelationValueRoute = ComponentsRelationValueRouteImport.update({
  id: '/components/relation-value',
  path: '/components/relation-value',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsResizablePanelRoute =
  ComponentsResizablePanelRouteImport.update({
    id: '/components/resizable-panel',
    path: '/components/resizable-panel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsSearchRoute = ComponentsSearchRouteImport.update({
  id: '/components/search',
  path: '/components/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSegmentedControlRoute =
  ComponentsSegmentedControlRouteImport.update({
    id: '/components/segmented-control',
    path: '/components/segmented-control',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSidePanelRoute = ComponentsSidePanelRouteImport.update({
  id: '/components/side-panel',
  path: '/components/side-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSpinnerRoute = ComponentsSpinnerRouteImport.update({
  id: '/components/spinner',
  path: '/components/spinner',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsStructuredValuePreviewRoute =
  ComponentsStructuredValuePreviewRouteImport.update({
    id: '/components/structured-value-preview',
    path: '/components/structured-value-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsSwitchRoute = ComponentsSwitchRouteImport.update({
  id: '/components/switch',
  path: '/components/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTabViewRoute = ComponentsTabViewRouteImport.update({
  id: '/components/tab-view',
  path: '/components/tab-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTextFieldRoute = ComponentsTextFieldRouteImport.update({
  id: '/components/text-field',
  path: '/components/text-field',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTextLinkRoute = ComponentsTextLinkRouteImport.update({
  id: '/components/text-link',
  path: '/components/text-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTextareaRoute = ComponentsTextareaRouteImport.update({
  id: '/components/textarea',
  path: '/components/textarea',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTimestampValueRoute =
  ComponentsTimestampValueRouteImport.update({
    id: '/components/timestamp-value',
    path: '/components/timestamp-value',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsToastRoute = ComponentsToastRouteImport.update({
  id: '/components/toast',
  path: '/components/toast',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsToggleGroupRoute = ComponentsToggleGroupRouteImport.update({
  id: '/components/toggle-group',
  path: '/components/toggle-group',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTooltipRoute = ComponentsTooltipRouteImport.update({
  id: '/components/tooltip',
  path: '/components/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsColorsRoute = FoundationsColorsRouteImport.update({
  id: '/foundations/colors',
  path: '/foundations/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsTypographyRoute = FoundationsTypographyRouteImport.update({
  id: '/foundations/typography',
  path: '/foundations/typography',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/action-list': typeof ComponentsActionListRoute
  '/components/binary-value': typeof ComponentsBinaryValueRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/button-group': typeof ComponentsButtonGroupRoute
  '/components/button-link': typeof ComponentsButtonLinkRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/code-editor': typeof ComponentsCodeEditorRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/context-menu': typeof ComponentsContextMenuRoute
  '/components/context-switcher': typeof ComponentsContextSwitcherRoute
  '/components/copy-button': typeof ComponentsCopyButtonRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/fieldset': typeof ComponentsFieldsetRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/input-group': typeof ComponentsInputGroupRoute
  '/components/json-view': typeof ComponentsJsonViewRoute
  '/components/keyboard-input': typeof ComponentsKeyboardInputRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/relation-value': typeof ComponentsRelationValueRoute
  '/components/resizable-panel': typeof ComponentsResizablePanelRoute
  '/components/search': typeof ComponentsSearchRoute
  '/components/segmented-control': typeof ComponentsSegmentedControlRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/side-panel': typeof ComponentsSidePanelRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/structured-value-preview': typeof ComponentsStructuredValuePreviewRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/tab-view': typeof ComponentsTabViewRoute
  '/components/text-field': typeof ComponentsTextFieldRoute
  '/components/text-link': typeof ComponentsTextLinkRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/timestamp-value': typeof ComponentsTimestampValueRoute
  '/components/toast': typeof ComponentsToastRoute
  '/components/toggle-group': typeof ComponentsToggleGroupRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/foundations/colors': typeof FoundationsColorsRoute
  '/foundations/typography': typeof FoundationsTypographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/action-list': typeof ComponentsActionListRoute
  '/components/binary-value': typeof ComponentsBinaryValueRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/button-group': typeof ComponentsButtonGroupRoute
  '/components/button-link': typeof ComponentsButtonLinkRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/code-editor': typeof ComponentsCodeEditorRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/context-menu': typeof ComponentsContextMenuRoute
  '/components/context-switcher': typeof ComponentsContextSwitcherRoute
  '/components/copy-button': typeof ComponentsCopyButtonRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/fieldset': typeof ComponentsFieldsetRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/input-group': typeof ComponentsInputGroupRoute
  '/components/json-view': typeof ComponentsJsonViewRoute
  '/components/keyboard-input': typeof ComponentsKeyboardInputRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/relation-value': typeof ComponentsRelationValueRoute
  '/components/resizable-panel': typeof ComponentsResizablePanelRoute
  '/components/search': typeof ComponentsSearchRoute
  '/components/segmented-control': typeof ComponentsSegmentedControlRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/side-panel': typeof ComponentsSidePanelRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/structured-value-preview': typeof ComponentsStructuredValuePreviewRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/tab-view': typeof ComponentsTabViewRoute
  '/components/text-field': typeof ComponentsTextFieldRoute
  '/components/text-link': typeof ComponentsTextLinkRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/timestamp-value': typeof ComponentsTimestampValueRoute
  '/components/toast': typeof ComponentsToastRoute
  '/components/toggle-group': typeof ComponentsToggleGroupRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/foundations/colors': typeof FoundationsColorsRoute
  '/foundations/typography': typeof FoundationsTypographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/action-list': typeof ComponentsActionListRoute
  '/components/binary-value': typeof ComponentsBinaryValueRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/button-group': typeof ComponentsButtonGroupRoute
  '/components/button-link': typeof ComponentsButtonLinkRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/code-editor': typeof ComponentsCodeEditorRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/context-menu': typeof ComponentsContextMenuRoute
  '/components/context-switcher': typeof ComponentsContextSwitcherRoute
  '/components/copy-button': typeof ComponentsCopyButtonRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/fieldset': typeof ComponentsFieldsetRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/input-group': typeof ComponentsInputGroupRoute
  '/components/json-view': typeof ComponentsJsonViewRoute
  '/components/keyboard-input': typeof ComponentsKeyboardInputRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/relation-value': typeof ComponentsRelationValueRoute
  '/components/resizable-panel': typeof ComponentsResizablePanelRoute
  '/components/search': typeof ComponentsSearchRoute
  '/components/segmented-control': typeof ComponentsSegmentedControlRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/side-panel': typeof ComponentsSidePanelRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/structured-value-preview': typeof ComponentsStructuredValuePreviewRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/tab-view': typeof ComponentsTabViewRoute
  '/components/text-field': typeof ComponentsTextFieldRoute
  '/components/text-link': typeof ComponentsTextLinkRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/timestamp-value': typeof ComponentsTimestampValueRoute
  '/components/toast': typeof ComponentsToastRoute
  '/components/toggle-group': typeof ComponentsToggleGroupRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/foundations/colors': typeof FoundationsColorsRoute
  '/foundations/typography': typeof FoundationsTypographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/accordion'
    | '/components/action-list'
    | '/components/binary-value'
    | '/components/button'
    | '/components/button-group'
    | '/components/button-link'
    | '/components/checkbox'
    | '/components/code-editor'
    | '/components/combobox'
    | '/components/context-menu'
    | '/components/context-switcher'
    | '/components/copy-button'
    | '/components/data-table'
    | '/components/field'
    | '/components/fieldset'
    | '/components/input'
    | '/components/input-group'
    | '/components/json-view'
    | '/components/keyboard-input'
    | '/components/menu'
    | '/components/relation-value'
    | '/components/resizable-panel'
    | '/components/search'
    | '/components/segmented-control'
    | '/components/select'
    | '/components/side-panel'
    | '/components/spinner'
    | '/components/structured-value-preview'
    | '/components/switch'
    | '/components/tab-view'
    | '/components/text-field'
    | '/components/text-link'
    | '/components/textarea'
    | '/components/timestamp-value'
    | '/components/toast'
    | '/components/toggle-group'
    | '/components/tooltip'
    | '/foundations/colors'
    | '/foundations/typography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/accordion'
    | '/components/action-list'
    | '/components/binary-value'
    | '/components/button'
    | '/components/button-group'
    | '/components/button-link'
    | '/components/checkbox'
    | '/components/code-editor'
    | '/components/combobox'
    | '/components/context-menu'
    | '/components/context-switcher'
    | '/components/copy-button'
    | '/components/data-table'
    | '/components/field'
    | '/components/fieldset'
    | '/components/input'
    | '/components/input-group'
    | '/components/json-view'
    | '/components/keyboard-input'
    | '/components/menu'
    | '/components/relation-value'
    | '/components/resizable-panel'
    | '/components/search'
    | '/components/segmented-control'
    | '/components/select'
    | '/components/side-panel'
    | '/components/spinner'
    | '/components/structured-value-preview'
    | '/components/switch'
    | '/components/tab-view'
    | '/components/text-field'
    | '/components/text-link'
    | '/components/textarea'
    | '/components/timestamp-value'
    | '/components/toast'
    | '/components/toggle-group'
    | '/components/tooltip'
    | '/foundations/colors'
    | '/foundations/typography'
  id:
    | '__root__'
    | '/'
    | '/components/accordion'
    | '/components/action-list'
    | '/components/binary-value'
    | '/components/button'
    | '/components/button-group'
    | '/components/button-link'
    | '/components/checkbox'
    | '/components/code-editor'
    | '/components/combobox'
    | '/components/context-menu'
    | '/components/context-switcher'
    | '/components/copy-button'
    | '/components/data-table'
    | '/components/field'
    | '/components/fieldset'
    | '/components/input'
    | '/components/input-group'
    | '/components/json-view'
    | '/components/keyboard-input'
    | '/components/menu'
    | '/components/relation-value'
    | '/components/resizable-panel'
    | '/components/search'
    | '/components/segmented-control'
    | '/components/select'
    | '/components/side-panel'
    | '/components/spinner'
    | '/components/structured-value-preview'
    | '/components/switch'
    | '/components/tab-view'
    | '/components/text-field'
    | '/components/text-link'
    | '/components/textarea'
    | '/components/timestamp-value'
    | '/components/toast'
    | '/components/toggle-group'
    | '/components/tooltip'
    | '/foundations/colors'
    | '/foundations/typography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsAccordionRoute: typeof ComponentsAccordionRoute
  ComponentsActionListRoute: typeof ComponentsActionListRoute
  ComponentsBinaryValueRoute: typeof ComponentsBinaryValueRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsButtonGroupRoute: typeof ComponentsButtonGroupRoute
  ComponentsButtonLinkRoute: typeof ComponentsButtonLinkRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsCodeEditorRoute: typeof ComponentsCodeEditorRoute
  ComponentsComboboxRoute: typeof ComponentsComboboxRoute
  ComponentsContextMenuRoute: typeof ComponentsContextMenuRoute
  ComponentsContextSwitcherRoute: typeof ComponentsContextSwitcherRoute
  ComponentsCopyButtonRoute: typeof ComponentsCopyButtonRoute
  ComponentsDataTableRoute: typeof ComponentsDataTableRoute
  ComponentsFieldRoute: typeof ComponentsFieldRoute
  ComponentsFieldsetRoute: typeof ComponentsFieldsetRoute
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsInputGroupRoute: typeof ComponentsInputGroupRoute
  ComponentsJsonViewRoute: typeof ComponentsJsonViewRoute
  ComponentsKeyboardInputRoute: typeof ComponentsKeyboardInputRoute
  ComponentsMenuRoute: typeof ComponentsMenuRoute
  ComponentsRelationValueRoute: typeof ComponentsRelationValueRoute
  ComponentsResizablePanelRoute: typeof ComponentsResizablePanelRoute
  ComponentsSearchRoute: typeof ComponentsSearchRoute
  ComponentsSegmentedControlRoute: typeof ComponentsSegmentedControlRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  ComponentsSidePanelRoute: typeof ComponentsSidePanelRoute
  ComponentsSpinnerRoute: typeof ComponentsSpinnerRoute
  ComponentsStructuredValuePreviewRoute: typeof ComponentsStructuredValuePreviewRoute
  ComponentsSwitchRoute: typeof ComponentsSwitchRoute
  ComponentsTabViewRoute: typeof ComponentsTabViewRoute
  ComponentsTextFieldRoute: typeof ComponentsTextFieldRoute
  ComponentsTextLinkRoute: typeof ComponentsTextLinkRoute
  ComponentsTextareaRoute: typeof ComponentsTextareaRoute
  ComponentsTimestampValueRoute: typeof ComponentsTimestampValueRoute
  ComponentsToastRoute: typeof ComponentsToastRoute
  ComponentsToggleGroupRoute: typeof ComponentsToggleGroupRoute
  ComponentsTooltipRoute: typeof ComponentsTooltipRoute
  FoundationsColorsRoute: typeof FoundationsColorsRoute
  FoundationsTypographyRoute: typeof FoundationsTypographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/accordion': {
      id: '/components/accordion'
      path: '/components/accordion'
      fullPath: '/components/accordion'
      preLoaderRoute: typeof ComponentsAccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/action-list': {
      id: '/components/action-list'
      path: '/components/action-list'
      fullPath: '/components/action-list'
      preLoaderRoute: typeof ComponentsActionListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/binary-value': {
      id: '/components/binary-value'
      path: '/components/binary-value'
      fullPath: '/components/binary-value'
      preLoaderRoute: typeof ComponentsBinaryValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button-group': {
      id: '/components/button-group'
      path: '/components/button-group'
      fullPath: '/components/button-group'
      preLoaderRoute: typeof ComponentsButtonGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button-link': {
      id: '/components/button-link'
      path: '/components/button-link'
      fullPath: '/components/button-link'
      preLoaderRoute: typeof ComponentsButtonLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/code-editor': {
      id: '/components/code-editor'
      path: '/components/code-editor'
      fullPath: '/components/code-editor'
      preLoaderRoute: typeof ComponentsCodeEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/combobox': {
      id: '/components/combobox'
      path: '/components/combobox'
      fullPath: '/components/combobox'
      preLoaderRoute: typeof ComponentsComboboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/context-menu': {
      id: '/components/context-menu'
      path: '/components/context-menu'
      fullPath: '/components/context-menu'
      preLoaderRoute: typeof ComponentsContextMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/context-switcher': {
      id: '/components/context-switcher'
      path: '/components/context-switcher'
      fullPath: '/components/context-switcher'
      preLoaderRoute: typeof ComponentsContextSwitcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/copy-button': {
      id: '/components/copy-button'
      path: '/components/copy-button'
      fullPath: '/components/copy-button'
      preLoaderRoute: typeof ComponentsCopyButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/data-table': {
      id: '/components/data-table'
      path: '/components/data-table'
      fullPath: '/components/data-table'
      preLoaderRoute: typeof ComponentsDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/field': {
      id: '/components/field'
      path: '/components/field'
      fullPath: '/components/field'
      preLoaderRoute: typeof ComponentsFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/fieldset': {
      id: '/components/fieldset'
      path: '/components/fieldset'
      fullPath: '/components/fieldset'
      preLoaderRoute: typeof ComponentsFieldsetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/input': {
      id: '/components/input'
      path: '/components/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/input-group': {
      id: '/components/input-group'
      path: '/components/input-group'
      fullPath: '/components/input-group'
      preLoaderRoute: typeof ComponentsInputGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/json-view': {
      id: '/components/json-view'
      path: '/components/json-view'
      fullPath: '/components/json-view'
      preLoaderRoute: typeof ComponentsJsonViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/keyboard-input': {
      id: '/components/keyboard-input'
      path: '/components/keyboard-input'
      fullPath: '/components/keyboard-input'
      preLoaderRoute: typeof ComponentsKeyboardInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/menu': {
      id: '/components/menu'
      path: '/components/menu'
      fullPath: '/components/menu'
      preLoaderRoute: typeof ComponentsMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/relation-value': {
      id: '/components/relation-value'
      path: '/components/relation-value'
      fullPath: '/components/relation-value'
      preLoaderRoute: typeof ComponentsRelationValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/resizable-panel': {
      id: '/components/resizable-panel'
      path: '/components/resizable-panel'
      fullPath: '/components/resizable-panel'
      preLoaderRoute: typeof ComponentsResizablePanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/search': {
      id: '/components/search'
      path: '/components/search'
      fullPath: '/components/search'
      preLoaderRoute: typeof ComponentsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/segmented-control': {
      id: '/components/segmented-control'
      path: '/components/segmented-control'
      fullPath: '/components/segmented-control'
      preLoaderRoute: typeof ComponentsSegmentedControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/select': {
      id: '/components/select'
      path: '/components/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/side-panel': {
      id: '/components/side-panel'
      path: '/components/side-panel'
      fullPath: '/components/side-panel'
      preLoaderRoute: typeof ComponentsSidePanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/spinner': {
      id: '/components/spinner'
      path: '/components/spinner'
      fullPath: '/components/spinner'
      preLoaderRoute: typeof ComponentsSpinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/structured-value-preview': {
      id: '/components/structured-value-preview'
      path: '/components/structured-value-preview'
      fullPath: '/components/structured-value-preview'
      preLoaderRoute: typeof ComponentsStructuredValuePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/switch': {
      id: '/components/switch'
      path: '/components/switch'
      fullPath: '/components/switch'
      preLoaderRoute: typeof ComponentsSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tab-view': {
      id: '/components/tab-view'
      path: '/components/tab-view'
      fullPath: '/components/tab-view'
      preLoaderRoute: typeof ComponentsTabViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/text-field': {
      id: '/components/text-field'
      path: '/components/text-field'
      fullPath: '/components/text-field'
      preLoaderRoute: typeof ComponentsTextFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/text-link': {
      id: '/components/text-link'
      path: '/components/text-link'
      fullPath: '/components/text-link'
      preLoaderRoute: typeof ComponentsTextLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/textarea': {
      id: '/components/textarea'
      path: '/components/textarea'
      fullPath: '/components/textarea'
      preLoaderRoute: typeof ComponentsTextareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/timestamp-value': {
      id: '/components/timestamp-value'
      path: '/components/timestamp-value'
      fullPath: '/components/timestamp-value'
      preLoaderRoute: typeof ComponentsTimestampValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/toast': {
      id: '/components/toast'
      path: '/components/toast'
      fullPath: '/components/toast'
      preLoaderRoute: typeof ComponentsToastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/toggle-group': {
      id: '/components/toggle-group'
      path: '/components/toggle-group'
      fullPath: '/components/toggle-group'
      preLoaderRoute: typeof ComponentsToggleGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tooltip': {
      id: '/components/tooltip'
      path: '/components/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/colors': {
      id: '/foundations/colors'
      path: '/foundations/colors'
      fullPath: '/foundations/colors'
      preLoaderRoute: typeof FoundationsColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/typography': {
      id: '/foundations/typography'
      path: '/foundations/typography'
      fullPath: '/foundations/typography'
      preLoaderRoute: typeof FoundationsTypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsAccordionRoute: ComponentsAccordionRoute,
  ComponentsActionListRoute: ComponentsActionListRoute,
  ComponentsBinaryValueRoute: ComponentsBinaryValueRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsButtonGroupRoute: ComponentsButtonGroupRoute,
  ComponentsButtonLinkRoute: ComponentsButtonLinkRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsCodeEditorRoute: ComponentsCodeEditorRoute,
  ComponentsComboboxRoute: ComponentsComboboxRoute,
  ComponentsContextMenuRoute: ComponentsContextMenuRoute,
  ComponentsContextSwitcherRoute: ComponentsContextSwitcherRoute,
  ComponentsCopyButtonRoute: ComponentsCopyButtonRoute,
  ComponentsDataTableRoute: ComponentsDataTableRoute,
  ComponentsFieldRoute: ComponentsFieldRoute,
  ComponentsFieldsetRoute: ComponentsFieldsetRoute,
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsInputGroupRoute: ComponentsInputGroupRoute,
  ComponentsJsonViewRoute: ComponentsJsonViewRoute,
  ComponentsKeyboardInputRoute: ComponentsKeyboardInputRoute,
  ComponentsMenuRoute: ComponentsMenuRoute,
  ComponentsRelationValueRoute: ComponentsRelationValueRoute,
  ComponentsResizablePanelRoute: ComponentsResizablePanelRoute,
  ComponentsSearchRoute: ComponentsSearchRoute,
  ComponentsSegmentedControlRoute: ComponentsSegmentedControlRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  ComponentsSidePanelRoute: ComponentsSidePanelRoute,
  ComponentsSpinnerRoute: ComponentsSpinnerRoute,
  ComponentsStructuredValuePreviewRoute: ComponentsStructuredValuePreviewRoute,
  ComponentsSwitchRoute: ComponentsSwitchRoute,
  ComponentsTabViewRoute: ComponentsTabViewRoute,
  ComponentsTextFieldRoute: ComponentsTextFieldRoute,
  ComponentsTextLinkRoute: ComponentsTextLinkRoute,
  ComponentsTextareaRoute: ComponentsTextareaRoute,
  ComponentsTimestampValueRoute: ComponentsTimestampValueRoute,
  ComponentsToastRoute: ComponentsToastRoute,
  ComponentsToggleGroupRoute: ComponentsToggleGroupRoute,
  ComponentsTooltipRoute: ComponentsTooltipRoute,
  FoundationsColorsRoute: FoundationsColorsRoute,
  FoundationsTypographyRoute: FoundationsTypographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
