import * as stylex from "@stylexjs/stylex";

import { layerIndexes } from "../../tokens/layers.stylex";
import { backgroundColors, borderColors, textColors } from "../../tokens/semantics.stylex";
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from "../../tokens/value.stylex";

export const menuStyles = stylex.create({
  trigger: {
    borderColor: borderColors.border,
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    gap: spacing.s,
    paddingInline: spacing.l,
    alignItems: "center",
    appearance: "none",
    backgroundColor: {
      default: backgroundColors["bg-card"],
      ":hover": backgroundColors["bg-secondary"],
      ":active": backgroundColors["bg-pressed"],
    },
    color: textColors["text-default"],
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    justifyContent: "center",
    lineHeight: lineHeights.none,
    outlineColor: borderColors["border-focused"],
    outlineOffset: -1,
    outlineStyle: "solid",
    outlineWidth: { default: 0, ":focus-visible": 2 },
    userSelect: "none",
    whiteSpace: "nowrap",
    height: 28,
  },
  triggerOpen: { backgroundColor: backgroundColors["bg-selected"] },
  disabled: { color: textColors["text-disabled"], cursor: "not-allowed" },
  positioner: { outline: "none", zIndex: layerIndexes.popup },
  popup: {
    borderColor: borderColors.border,
    borderRadius: borderRadii.s,
    borderStyle: "solid",
    borderWidth: 1,
    outline: "none",
    paddingBlock: spacing.xxs,
    backgroundColor: backgroundColors["bg-popover"],
    color: textColors["text-default"],
    transformOrigin: "var(--transform-origin)",
    maxWidth: "var(--available-width)",
  },
  popupWidthContent: { minWidth: 160, width: "max-content" },
  popupWidthAnchor: { width: "var(--anchor-width)" },
  popupTransition: { opacity: 0, transform: "scale(0.98)" },
  item: {
    borderRadius: borderRadii.xs,
    gap: spacing.m,
    marginInline: spacing.xxs,
    outline: "none",
    paddingInline: spacing.xs,
    alignItems: "center",
    boxSizing: "border-box",
    cursor: "default",
    display: "flex",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.none,
    userSelect: "none",
    minHeight: 26,
    width: "auto",
  },
  itemHighlighted: {
    backgroundColor: backgroundColors["bg-secondary"],
  },
  itemDisabled: { color: textColors["text-disabled"] },
  itemDanger: { color: textColors["fg-danger"] },
  itemDangerHighlighted: {
    backgroundColor: backgroundColors["bg-danger"],
    color: textColors["fg-inverse"],
  },
  checkItem: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 16px" },
  indicator: {
    alignItems: "center",
    display: "inline-flex",
    gridColumnStart: "2",
    gridRowStart: "1",
    justifyContent: "center",
    justifySelf: "end",
  },
  icon: { display: "block", height: 14, width: 14 },
  shortcut: {
    color: textColors["text-subtle"],
    flexShrink: 0,
    fontSize: fontSizes[1],
    marginInlineStart: "auto",
  },
  groupLabel: {
    marginInline: spacing.xxs,
    paddingBlock: spacing.xxs,
    paddingInline: spacing.xs,
    color: textColors["text-subtle"],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.tight,
  },
  separator: {
    marginBlock: spacing.xs,
    marginInline: spacing.none,
    backgroundColor: borderColors["border-secondary"],
    height: 1,
  },
});
