import * as stylex from '@stylexjs/stylex'

import { layerIndexes } from '../../tokens/layers.stylex'
import {
  borderColors,
  dangerElementColors,
  focusColors,
  ghostElementColors,
  spatial,
  surfaceColors,
  textColors,
} from '../../tokens/semantics.stylex'
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  shadows,
  spacing,
} from '../../tokens/value.stylex'
import { keyboardInputVars } from '../keyboardInput/keyboardInputVars.stylex'

export const menuStyles = stylex.create({
  trigger: {
    borderColor: borderColors.default,
    borderRadius: borderRadii.xs,
    borderStyle: 'solid',
    borderWidth: 1,
    gap: spacing.s,
    paddingInline: spacing.s,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: {
      default: surfaceColors.default,
      ':hover': ghostElementColors.hover,
      ':active': ghostElementColors.pressed,
    },
    color: textColors.default,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    justifyContent: 'center',
    lineHeight: lineHeights.ui,
    outlineColor: focusColors.ring,
    outlineOffset: `calc(-1 * ${spatial['focus-ring-width']})`,
    outlineStyle: 'solid',
    outlineWidth: { default: 0, ':focus-visible': spatial['focus-ring-width'] },
    userSelect: 'none',
    whiteSpace: 'nowrap',
    height: spatial['control-height-l'],
  },
  triggerGrouped: {
    borderRadius: 0,
    backgroundColor: {
      default: 'transparent',
      ':hover': ghostElementColors.hover,
      ':active': ghostElementColors.pressed,
    },
    borderBlockEndWidth: 0,
    borderBlockStartWidth: 0,
    borderInlineEndWidth: 0,
    borderInlineStartColor: borderColors.subtle,
    borderInlineStartStyle: 'solid',
    borderInlineStartWidth: 1,
    height: '100%',
  },
  triggerOpen: { backgroundColor: ghostElementColors.selected },
  triggerPressed: {},
  triggerDisabled: {},
  disabled: {
    backgroundColor: {
      default: surfaceColors.default,
      ':hover': surfaceColors.default,
      ':active': surfaceColors.default,
    },
    color: textColors.disabled,
    cursor: 'not-allowed',
  },
  positioner: { outline: 'none', zIndex: layerIndexes.popup },
  positionerOpen: {},
  positionerClosed: {},
  positionerSideTop: {},
  positionerSideBottom: {},
  positionerSideLeft: {},
  positionerSideRight: {},
  positionerSideInlineStart: {},
  positionerSideInlineEnd: {},
  positionerAlignStart: {},
  positionerAlignCenter: {},
  positionerAlignEnd: {},
  positionerAnchorHidden: {},
  positionerNested: {},
  positionerInstant: {},
  popup: {
    padding: spatial['popup-collection-padding'],
    borderColor: borderColors.default,
    borderRadius: borderRadii.xs,
    borderStyle: 'solid',
    borderWidth: 1,
    outline: 'none',
    overscrollBehavior: 'contain',
    backgroundColor: surfaceColors.raised,
    boxShadow: shadows.medium,
    color: textColors.default,
    transformOrigin: 'var(--transform-origin)',
    maxHeight: 'var(--available-height)',
    maxWidth: 'var(--available-width)',
    overflowY: 'auto',
  },
  popupWidthContent: { minWidth: spatial['menu-min-width'], width: 'max-content' },
  popupWidthAnchor: { width: 'var(--anchor-width)' },
  popupTransition: { opacity: 0, transform: 'scale(0.98)' },
  popupOpen: {},
  popupClosed: {},
  popupStarting: {},
  popupEnding: {},
  popupSideTop: {},
  popupSideBottom: {},
  popupSideLeft: {},
  popupSideRight: {},
  popupSideInlineStart: {},
  popupSideInlineEnd: {},
  popupAlignStart: {},
  popupAlignCenter: {},
  popupAlignEnd: {},
  popupNested: {},
  popupInstant: {},
  item: {
    borderRadius: borderRadii.xs,
    gap: spacing.s,
    outline: 'none',
    paddingInline: spatial['popup-item-inline-padding'],
    alignItems: 'center',
    backgroundColor: { default: 'transparent', ':active': ghostElementColors.hover },
    boxSizing: 'border-box',
    color: textColors.default,
    cursor: 'default',
    display: 'flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.ui,
    userSelect: 'none',
    minHeight: spatial['collection-row-height-s'],
    width: 'auto',
  },
  itemHighlighted: {
    [keyboardInputVars.textColor]: textColors.default,
    backgroundColor: ghostElementColors.hover,
    outlineColor: { default: 'transparent', '@media (forced-colors: active)': 'Highlight' },
    outlineStyle: 'solid',
    outlineWidth: { default: 0, '@media (forced-colors: active)': 1 },
  },
  itemDisabledState: {},
  itemSelected: { backgroundColor: ghostElementColors.selected },
  itemUnchecked: {},
  itemOpen: { backgroundColor: ghostElementColors.selected },
  itemDisabled: {
    [keyboardInputVars.textColor]: textColors.disabled,
    backgroundColor: { default: 'transparent', ':active': 'transparent' },
    color: textColors.disabled,
    cursor: 'not-allowed',
  },
  itemDanger: { color: textColors.danger },
  itemDangerHighlighted: {
    [keyboardInputVars.textColor]: textColors.danger,
    backgroundColor: dangerElementColors.subtle,
    color: textColors.danger,
  },
  choiceItem: {
    display: 'grid',
    gridTemplateColumns: `${spatial['icon-size-m']} minmax(0, 1fr) auto`,
  },
  indicator: {
    alignItems: 'center',
    display: 'inline-flex',
    gridColumnStart: '1',
    gridRowStart: '1',
    justifyContent: 'center',
    justifySelf: 'start',
  },
  checkboxIndicatorChecked: {},
  checkboxIndicatorUnchecked: {},
  checkboxIndicatorDisabled: {},
  checkboxIndicatorHighlighted: {},
  checkboxIndicatorStarting: {},
  checkboxIndicatorEnding: {},
  radioIndicatorChecked: {},
  radioIndicatorUnchecked: {},
  radioIndicatorDisabled: {},
  radioIndicatorHighlighted: {},
  radioIndicatorStarting: {},
  radioIndicatorEnding: {},
  radioGroupDisabled: {},
  icon: {
    display: 'block',
    height: spatial['icon-size-s'],
    width: spatial['icon-size-s'],
  },
  prefix: {
    alignItems: 'center',
    display: 'inline-flex',
    flexShrink: 0,
    justifyContent: 'center',
    width: spatial['icon-size-m'],
  },
  suffix: {
    alignItems: 'center',
    display: 'inline-flex',
    flexShrink: 0,
    justifyContent: 'center',
    marginInlineStart: 'auto',
  },
  submenuIcon: {
    display: 'block',
    height: spatial['icon-size-xs'],
    width: spatial['icon-size-xs'],
  },
  shortcut: {
    flexShrink: 0,
    marginInlineStart: 'auto',
  },
  groupLabel: {
    paddingBlock: spatial['popup-collection-padding'],
    paddingInline: spatial['popup-item-inline-padding'],
    color: textColors.muted,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.compact,
  },
  separator: {
    marginBlock: spatial['popup-collection-padding'],
    marginInline: spacing.none,
    backgroundColor: borderColors.subtle,
    height: 1,
  },
  separatorHorizontal: {},
  separatorVertical: {},
})
