import * as stylex from "@stylexjs/stylex";

import { layerIndexes } from "../../tokens/layers.stylex";
import { backgroundColors, borderColors, textColors } from "../../tokens/semantics.stylex";
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  shadows,
  spacing,
} from "../../tokens/value.stylex";
import { keyboardInputVars } from "../keyboardInput/keyboardInputVars.stylex";

export const menuStyles = stylex.create({
  trigger: {
    borderColor: borderColors.border,
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    gap: spacing.s,
    paddingInline: spacing.m,
    alignItems: "center",
    appearance: "none",
    backgroundColor: {
      default: backgroundColors["bg-card"],
      ":hover": backgroundColors["bg-hover"],
      ":active": backgroundColors["bg-pressed"],
    },
    color: textColors["text-default"],
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    justifyContent: "center",
    lineHeight: lineHeights.none,
    outlineColor: borderColors["border-focused"],
    outlineOffset: -1,
    outlineStyle: "solid",
    outlineWidth: { default: 0, ":focus-visible": 2 },
    userSelect: "none",
    whiteSpace: "nowrap",
    height: 28,
  },
  triggerGrouped: {
    borderRadius: 0,
    backgroundColor: {
      default: "transparent",
      ":hover": backgroundColors["bg-hover"],
      ":active": backgroundColors["bg-pressed"],
    },
    borderBlockEndWidth: 0,
    borderBlockStartWidth: 0,
    borderInlineEndWidth: 0,
    borderInlineStartColor: borderColors["border-secondary"],
    borderInlineStartStyle: "solid",
    borderInlineStartWidth: 1,
    height: "100%",
  },
  triggerOpen: { backgroundColor: backgroundColors["bg-selected"] },
  disabled: {
    backgroundColor: {
      default: backgroundColors["bg-card"],
      ":hover": backgroundColors["bg-card"],
      ":active": backgroundColors["bg-card"],
    },
    color: textColors["text-disabled"],
    cursor: "not-allowed",
  },
  positioner: { outline: "none", zIndex: layerIndexes.popup },
  popup: {
    padding: spacing.xxs,
    borderColor: borderColors.border,
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    // gap: spacing.xxs,
    outline: "none",
    backgroundColor: backgroundColors["bg-popover"],
    boxShadow: shadows.medium,
    color: textColors["text-default"],
    transformOrigin: "var(--transform-origin)",
    maxWidth: "var(--available-width)",
  },
  popupWidthContent: { minWidth: 140, width: "max-content" },
  popupWidthAnchor: { width: "var(--anchor-width)" },
  popupTransition: { opacity: 0, transform: "scale(0.98)" },
  item: {
    borderRadius: borderRadii.xs,
    gap: spacing.m,
    outline: "none",
    paddingInline: spacing.s,
    alignItems: "center",
    backgroundColor: { default: "transparent", ":active": backgroundColors["bg-hover"] },
    boxSizing: "border-box",
    color: textColors["text-default"],
    cursor: "default",
    display: "flex",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.none,
    userSelect: "none",
    minHeight: 24,
    width: "auto",
  },
  itemHighlighted: {
    [keyboardInputVars.textColor]: textColors["text-default"],
    backgroundColor: backgroundColors["bg-hover"],
  },
  itemSelected: { backgroundColor: backgroundColors["bg-selected"] },
  itemOpen: { backgroundColor: backgroundColors["bg-selected"] },
  itemDisabled: {
    [keyboardInputVars.textColor]: textColors["text-disabled"],
    backgroundColor: { default: "transparent", ":active": "transparent" },
    color: textColors["text-disabled"],
    cursor: "not-allowed",
  },
  itemDanger: { color: textColors["text-danger"] },
  itemDangerHighlighted: {
    [keyboardInputVars.textColor]: textColors["fg-danger"],
    backgroundColor: backgroundColors["bg-danger"],
    color: textColors["fg-danger"],
  },
  choiceItem: { display: "grid", gridTemplateColumns: "16px minmax(0, 1fr) auto" },
  indicator: {
    alignItems: "center",
    display: "inline-flex",
    gridColumnStart: "1",
    gridRowStart: "1",
    justifyContent: "center",
    justifySelf: "start",
  },
  icon: { display: "block", height: 14, width: 14 },
  prefix: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    justifyContent: "center",
    width: 16,
  },
  suffix: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    justifyContent: "center",
    marginInlineStart: "auto",
  },
  submenuIcon: { display: "block", height: 12, width: 12 },
  shortcut: {
    color: textColors["text-subtle"],
    flexShrink: 0,
    fontSize: fontSizes[1],
    marginInlineStart: "auto",
  },
  groupLabel: {
    marginInline: spacing.xxs,
    paddingBlock: spacing.xxs,
    paddingInline: spacing.xxs,
    color: textColors["text-subtle"],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.tight,
  },
  separator: {
    marginBlock: spacing.xxs,
    marginInline: spacing.none,
    backgroundColor: borderColors["border-secondary"],
    height: 1,
  },
});
