import * as stylex from '@stylexjs/stylex'

import { layerIndexes } from '../../tokens/layers.stylex'
import { spatial, surfaceColors, textColors } from '../../tokens/semantics.stylex'
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  shadows,
  spacing,
} from '../../tokens/value.stylex'

export const alertDialogStyles = stylex.create({
  backdrop: {
    inset: 0,
    backgroundColor: surfaceColors.backdrop,
    position: 'fixed',
    zIndex: layerIndexes.modal,
  },
  backdropOpen: {},
  backdropClosed: {},
  backdropStarting: {},
  backdropEnding: {},
  viewport: {
    inset: 0,
    padding: spacing.xl,
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    position: 'fixed',
    zIndex: layerIndexes.modal,
    overflowY: 'auto',
  },
  viewportOpen: {},
  viewportClosed: {},
  viewportNested: {},
  viewportNestedDialogOpen: {},
  viewportStarting: {},
  viewportEnding: {},
  popup: {
    padding: spacing.m,
    borderRadius: borderRadii.s,
    gap: spacing.s,
    outline: 'none',
    backgroundColor: surfaceColors.raised,
    boxShadow: shadows.medium,
    boxSizing: 'border-box',
    color: textColors.default,
    display: 'flex',
    flexDirection: 'column',
    maxWidth: spatial['popup-width-l'],
    width: '100%',
  },
  popupOpen: {},
  popupClosed: {},
  popupNested: {},
  popupNestedDialogOpen: {},
  popupStarting: {},
  popupEnding: {},
  title: {
    margin: 0,
    color: textColors.default,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[3],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.normal,
  },
  description: {
    margin: 0,
    color: textColors.muted,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.ui,
  },
  actions: {
    gap: spacing.s,
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  closeEnabled: {},
  closeDisabled: {},
})
