/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnRouteImport } from './routes/conn'
import { Route as ConnConnectionIdRouteImport } from './routes/conn/$connectionId'
import { Route as ConnNewRouteImport } from './routes/conn/new'
import { Route as ConnConnectionIdIndexRouteImport } from './routes/conn/$connectionId/index'
import { Route as ConnConnectionIdLiveQueriesRouteImport } from './routes/conn/$connectionId/live-queries'
import { Route as ConnConnectionIdTablesRouteImport } from './routes/conn/$connectionId/tables'
import { Route as ConnEditConnectionIdRouteImport } from './routes/conn/edit/$connectionId'
import { Route as ConnConnectionIdLiveQueriesIndexRouteImport } from './routes/conn/$connectionId/live-queries/index'
import { Route as ConnConnectionIdTablesIndexRouteImport } from './routes/conn/$connectionId/tables/index'
import { Route as ConnConnectionIdTablesTableNameIndexRouteImport } from './routes/conn/$connectionId/tables/$tableName/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnRoute = ConnRouteImport.update({
  id: '/conn',
  path: '/conn',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnConnectionIdRoute = ConnConnectionIdRouteImport.update({
  id: '/$connectionId',
  path: '/$connectionId',
  getParentRoute: () => ConnRoute,
} as any)
const ConnNewRoute = ConnNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ConnRoute,
} as any)
const ConnConnectionIdIndexRoute = ConnConnectionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnConnectionIdRoute,
} as any)
const ConnConnectionIdLiveQueriesRoute =
  ConnConnectionIdLiveQueriesRouteImport.update({
    id: '/live-queries',
    path: '/live-queries',
    getParentRoute: () => ConnConnectionIdRoute,
  } as any)
const ConnConnectionIdTablesRoute = ConnConnectionIdTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => ConnConnectionIdRoute,
} as any)
const ConnEditConnectionIdRoute = ConnEditConnectionIdRouteImport.update({
  id: '/edit/$connectionId',
  path: '/edit/$connectionId',
  getParentRoute: () => ConnRoute,
} as any)
const ConnConnectionIdLiveQueriesIndexRoute =
  ConnConnectionIdLiveQueriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnConnectionIdLiveQueriesRoute,
  } as any)
const ConnConnectionIdTablesIndexRoute =
  ConnConnectionIdTablesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnConnectionIdTablesRoute,
  } as any)
const ConnConnectionIdTablesTableNameIndexRoute =
  ConnConnectionIdTablesTableNameIndexRouteImport.update({
    id: '/$tableName/',
    path: '/$tableName/',
    getParentRoute: () => ConnConnectionIdTablesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conn': typeof ConnRouteWithChildren
  '/conn/$connectionId': typeof ConnConnectionIdRouteWithChildren
  '/conn/new': typeof ConnNewRoute
  '/conn/$connectionId/live-queries': typeof ConnConnectionIdLiveQueriesRouteWithChildren
  '/conn/$connectionId/tables': typeof ConnConnectionIdTablesRouteWithChildren
  '/conn/edit/$connectionId': typeof ConnEditConnectionIdRoute
  '/conn/$connectionId/': typeof ConnConnectionIdIndexRoute
  '/conn/$connectionId/live-queries/': typeof ConnConnectionIdLiveQueriesIndexRoute
  '/conn/$connectionId/tables/': typeof ConnConnectionIdTablesIndexRoute
  '/conn/$connectionId/tables/$tableName/': typeof ConnConnectionIdTablesTableNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conn': typeof ConnRouteWithChildren
  '/conn/new': typeof ConnNewRoute
  '/conn/edit/$connectionId': typeof ConnEditConnectionIdRoute
  '/conn/$connectionId': typeof ConnConnectionIdIndexRoute
  '/conn/$connectionId/live-queries': typeof ConnConnectionIdLiveQueriesIndexRoute
  '/conn/$connectionId/tables': typeof ConnConnectionIdTablesIndexRoute
  '/conn/$connectionId/tables/$tableName': typeof ConnConnectionIdTablesTableNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conn': typeof ConnRouteWithChildren
  '/conn/$connectionId': typeof ConnConnectionIdRouteWithChildren
  '/conn/new': typeof ConnNewRoute
  '/conn/$connectionId/live-queries': typeof ConnConnectionIdLiveQueriesRouteWithChildren
  '/conn/$connectionId/tables': typeof ConnConnectionIdTablesRouteWithChildren
  '/conn/edit/$connectionId': typeof ConnEditConnectionIdRoute
  '/conn/$connectionId/': typeof ConnConnectionIdIndexRoute
  '/conn/$connectionId/live-queries/': typeof ConnConnectionIdLiveQueriesIndexRoute
  '/conn/$connectionId/tables/': typeof ConnConnectionIdTablesIndexRoute
  '/conn/$connectionId/tables/$tableName/': typeof ConnConnectionIdTablesTableNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conn'
    | '/conn/$connectionId'
    | '/conn/new'
    | '/conn/$connectionId/live-queries'
    | '/conn/$connectionId/tables'
    | '/conn/edit/$connectionId'
    | '/conn/$connectionId/'
    | '/conn/$connectionId/live-queries/'
    | '/conn/$connectionId/tables/'
    | '/conn/$connectionId/tables/$tableName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conn'
    | '/conn/new'
    | '/conn/edit/$connectionId'
    | '/conn/$connectionId'
    | '/conn/$connectionId/live-queries'
    | '/conn/$connectionId/tables'
    | '/conn/$connectionId/tables/$tableName'
  id:
    | '__root__'
    | '/'
    | '/conn'
    | '/conn/$connectionId'
    | '/conn/new'
    | '/conn/$connectionId/live-queries'
    | '/conn/$connectionId/tables'
    | '/conn/edit/$connectionId'
    | '/conn/$connectionId/'
    | '/conn/$connectionId/live-queries/'
    | '/conn/$connectionId/tables/'
    | '/conn/$connectionId/tables/$tableName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnRoute: typeof ConnRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conn': {
      id: '/conn'
      path: '/conn'
      fullPath: '/conn'
      preLoaderRoute: typeof ConnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conn/$connectionId': {
      id: '/conn/$connectionId'
      path: '/$connectionId'
      fullPath: '/conn/$connectionId'
      preLoaderRoute: typeof ConnConnectionIdRouteImport
      parentRoute: typeof ConnRoute
    }
    '/conn/new': {
      id: '/conn/new'
      path: '/new'
      fullPath: '/conn/new'
      preLoaderRoute: typeof ConnNewRouteImport
      parentRoute: typeof ConnRoute
    }
    '/conn/$connectionId/': {
      id: '/conn/$connectionId/'
      path: '/'
      fullPath: '/conn/$connectionId/'
      preLoaderRoute: typeof ConnConnectionIdIndexRouteImport
      parentRoute: typeof ConnConnectionIdRoute
    }
    '/conn/$connectionId/live-queries': {
      id: '/conn/$connectionId/live-queries'
      path: '/live-queries'
      fullPath: '/conn/$connectionId/live-queries'
      preLoaderRoute: typeof ConnConnectionIdLiveQueriesRouteImport
      parentRoute: typeof ConnConnectionIdRoute
    }
    '/conn/$connectionId/tables': {
      id: '/conn/$connectionId/tables'
      path: '/tables'
      fullPath: '/conn/$connectionId/tables'
      preLoaderRoute: typeof ConnConnectionIdTablesRouteImport
      parentRoute: typeof ConnConnectionIdRoute
    }
    '/conn/edit/$connectionId': {
      id: '/conn/edit/$connectionId'
      path: '/edit/$connectionId'
      fullPath: '/conn/edit/$connectionId'
      preLoaderRoute: typeof ConnEditConnectionIdRouteImport
      parentRoute: typeof ConnRoute
    }
    '/conn/$connectionId/live-queries/': {
      id: '/conn/$connectionId/live-queries/'
      path: '/'
      fullPath: '/conn/$connectionId/live-queries/'
      preLoaderRoute: typeof ConnConnectionIdLiveQueriesIndexRouteImport
      parentRoute: typeof ConnConnectionIdLiveQueriesRoute
    }
    '/conn/$connectionId/tables/': {
      id: '/conn/$connectionId/tables/'
      path: '/'
      fullPath: '/conn/$connectionId/tables/'
      preLoaderRoute: typeof ConnConnectionIdTablesIndexRouteImport
      parentRoute: typeof ConnConnectionIdTablesRoute
    }
    '/conn/$connectionId/tables/$tableName/': {
      id: '/conn/$connectionId/tables/$tableName/'
      path: '/$tableName'
      fullPath: '/conn/$connectionId/tables/$tableName/'
      preLoaderRoute: typeof ConnConnectionIdTablesTableNameIndexRouteImport
      parentRoute: typeof ConnConnectionIdTablesRoute
    }
  }
}

interface ConnConnectionIdLiveQueriesRouteChildren {
  ConnConnectionIdLiveQueriesIndexRoute: typeof ConnConnectionIdLiveQueriesIndexRoute
}

const ConnConnectionIdLiveQueriesRouteChildren: ConnConnectionIdLiveQueriesRouteChildren =
  {
    ConnConnectionIdLiveQueriesIndexRoute:
      ConnConnectionIdLiveQueriesIndexRoute,
  }

const ConnConnectionIdLiveQueriesRouteWithChildren =
  ConnConnectionIdLiveQueriesRoute._addFileChildren(
    ConnConnectionIdLiveQueriesRouteChildren,
  )

interface ConnConnectionIdTablesRouteChildren {
  ConnConnectionIdTablesIndexRoute: typeof ConnConnectionIdTablesIndexRoute
  ConnConnectionIdTablesTableNameIndexRoute: typeof ConnConnectionIdTablesTableNameIndexRoute
}

const ConnConnectionIdTablesRouteChildren: ConnConnectionIdTablesRouteChildren =
  {
    ConnConnectionIdTablesIndexRoute: ConnConnectionIdTablesIndexRoute,
    ConnConnectionIdTablesTableNameIndexRoute:
      ConnConnectionIdTablesTableNameIndexRoute,
  }

const ConnConnectionIdTablesRouteWithChildren =
  ConnConnectionIdTablesRoute._addFileChildren(
    ConnConnectionIdTablesRouteChildren,
  )

interface ConnConnectionIdRouteChildren {
  ConnConnectionIdLiveQueriesRoute: typeof ConnConnectionIdLiveQueriesRouteWithChildren
  ConnConnectionIdTablesRoute: typeof ConnConnectionIdTablesRouteWithChildren
  ConnConnectionIdIndexRoute: typeof ConnConnectionIdIndexRoute
}

const ConnConnectionIdRouteChildren: ConnConnectionIdRouteChildren = {
  ConnConnectionIdLiveQueriesRoute:
    ConnConnectionIdLiveQueriesRouteWithChildren,
  ConnConnectionIdTablesRoute: ConnConnectionIdTablesRouteWithChildren,
  ConnConnectionIdIndexRoute: ConnConnectionIdIndexRoute,
}

const ConnConnectionIdRouteWithChildren =
  ConnConnectionIdRoute._addFileChildren(ConnConnectionIdRouteChildren)

interface ConnRouteChildren {
  ConnConnectionIdRoute: typeof ConnConnectionIdRouteWithChildren
  ConnNewRoute: typeof ConnNewRoute
  ConnEditConnectionIdRoute: typeof ConnEditConnectionIdRoute
}

const ConnRouteChildren: ConnRouteChildren = {
  ConnConnectionIdRoute: ConnConnectionIdRouteWithChildren,
  ConnNewRoute: ConnNewRoute,
  ConnEditConnectionIdRoute: ConnEditConnectionIdRoute,
}

const ConnRouteWithChildren = ConnRoute._addFileChildren(ConnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnRoute: ConnRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
