/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnRouteImport } from './routes/conn'
import { Route as ConnConnectionIdRouteImport } from './routes/conn/$connectionId'
import { Route as ConnNewRouteImport } from './routes/conn/new'
import { Route as ConnConnectionIdIndexRouteImport } from './routes/conn/$connectionId/index'
import { Route as ConnConnectionIdQueriesRouteImport } from './routes/conn/$connectionId/queries'
import { Route as ConnConnectionIdTablesRouteImport } from './routes/conn/$connectionId/tables'
import { Route as ConnConnectionIdQueriesIndexRouteImport } from './routes/conn/$connectionId/queries/index'
import { Route as ConnConnectionIdTablesIndexRouteImport } from './routes/conn/$connectionId/tables/index'
import { Route as ConnConnectionIdTablesTableNameIndexRouteImport } from './routes/conn/$connectionId/tables/$tableName/index'

const ConnRoute = ConnRouteImport.update({
  id: '/conn',
  path: '/conn',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnConnectionIdRoute = ConnConnectionIdRouteImport.update({
  id: '/$connectionId',
  path: '/$connectionId',
  getParentRoute: () => ConnRoute,
} as any)
const ConnNewRoute = ConnNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ConnRoute,
} as any)
const ConnConnectionIdIndexRoute = ConnConnectionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnConnectionIdRoute,
} as any)
const ConnConnectionIdQueriesRoute = ConnConnectionIdQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => ConnConnectionIdRoute,
} as any)
const ConnConnectionIdTablesRoute = ConnConnectionIdTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => ConnConnectionIdRoute,
} as any)
const ConnConnectionIdQueriesIndexRoute =
  ConnConnectionIdQueriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnConnectionIdQueriesRoute,
  } as any)
const ConnConnectionIdTablesIndexRoute =
  ConnConnectionIdTablesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnConnectionIdTablesRoute,
  } as any)
const ConnConnectionIdTablesTableNameIndexRoute =
  ConnConnectionIdTablesTableNameIndexRouteImport.update({
    id: '/$tableName/',
    path: '/$tableName/',
    getParentRoute: () => ConnConnectionIdTablesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/conn': typeof ConnRouteWithChildren
  '/conn/$connectionId': typeof ConnConnectionIdRouteWithChildren
  '/conn/new': typeof ConnNewRoute
  '/conn/$connectionId/queries': typeof ConnConnectionIdQueriesRouteWithChildren
  '/conn/$connectionId/tables': typeof ConnConnectionIdTablesRouteWithChildren
  '/conn/$connectionId/': typeof ConnConnectionIdIndexRoute
  '/conn/$connectionId/queries/': typeof ConnConnectionIdQueriesIndexRoute
  '/conn/$connectionId/tables/': typeof ConnConnectionIdTablesIndexRoute
  '/conn/$connectionId/tables/$tableName/': typeof ConnConnectionIdTablesTableNameIndexRoute
}
export interface FileRoutesByTo {
  '/conn': typeof ConnRouteWithChildren
  '/conn/new': typeof ConnNewRoute
  '/conn/$connectionId': typeof ConnConnectionIdIndexRoute
  '/conn/$connectionId/queries': typeof ConnConnectionIdQueriesIndexRoute
  '/conn/$connectionId/tables': typeof ConnConnectionIdTablesIndexRoute
  '/conn/$connectionId/tables/$tableName': typeof ConnConnectionIdTablesTableNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/conn': typeof ConnRouteWithChildren
  '/conn/$connectionId': typeof ConnConnectionIdRouteWithChildren
  '/conn/new': typeof ConnNewRoute
  '/conn/$connectionId/queries': typeof ConnConnectionIdQueriesRouteWithChildren
  '/conn/$connectionId/tables': typeof ConnConnectionIdTablesRouteWithChildren
  '/conn/$connectionId/': typeof ConnConnectionIdIndexRoute
  '/conn/$connectionId/queries/': typeof ConnConnectionIdQueriesIndexRoute
  '/conn/$connectionId/tables/': typeof ConnConnectionIdTablesIndexRoute
  '/conn/$connectionId/tables/$tableName/': typeof ConnConnectionIdTablesTableNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/conn'
    | '/conn/$connectionId'
    | '/conn/new'
    | '/conn/$connectionId/queries'
    | '/conn/$connectionId/tables'
    | '/conn/$connectionId/'
    | '/conn/$connectionId/queries/'
    | '/conn/$connectionId/tables/'
    | '/conn/$connectionId/tables/$tableName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/conn'
    | '/conn/new'
    | '/conn/$connectionId'
    | '/conn/$connectionId/queries'
    | '/conn/$connectionId/tables'
    | '/conn/$connectionId/tables/$tableName'
  id:
    | '__root__'
    | '/conn'
    | '/conn/$connectionId'
    | '/conn/new'
    | '/conn/$connectionId/queries'
    | '/conn/$connectionId/tables'
    | '/conn/$connectionId/'
    | '/conn/$connectionId/queries/'
    | '/conn/$connectionId/tables/'
    | '/conn/$connectionId/tables/$tableName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConnRoute: typeof ConnRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/conn': {
      id: '/conn'
      path: '/conn'
      fullPath: '/conn'
      preLoaderRoute: typeof ConnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conn/$connectionId': {
      id: '/conn/$connectionId'
      path: '/$connectionId'
      fullPath: '/conn/$connectionId'
      preLoaderRoute: typeof ConnConnectionIdRouteImport
      parentRoute: typeof ConnRoute
    }
    '/conn/new': {
      id: '/conn/new'
      path: '/new'
      fullPath: '/conn/new'
      preLoaderRoute: typeof ConnNewRouteImport
      parentRoute: typeof ConnRoute
    }
    '/conn/$connectionId/': {
      id: '/conn/$connectionId/'
      path: '/'
      fullPath: '/conn/$connectionId/'
      preLoaderRoute: typeof ConnConnectionIdIndexRouteImport
      parentRoute: typeof ConnConnectionIdRoute
    }
    '/conn/$connectionId/queries': {
      id: '/conn/$connectionId/queries'
      path: '/queries'
      fullPath: '/conn/$connectionId/queries'
      preLoaderRoute: typeof ConnConnectionIdQueriesRouteImport
      parentRoute: typeof ConnConnectionIdRoute
    }
    '/conn/$connectionId/tables': {
      id: '/conn/$connectionId/tables'
      path: '/tables'
      fullPath: '/conn/$connectionId/tables'
      preLoaderRoute: typeof ConnConnectionIdTablesRouteImport
      parentRoute: typeof ConnConnectionIdRoute
    }
    '/conn/$connectionId/queries/': {
      id: '/conn/$connectionId/queries/'
      path: '/'
      fullPath: '/conn/$connectionId/queries/'
      preLoaderRoute: typeof ConnConnectionIdQueriesIndexRouteImport
      parentRoute: typeof ConnConnectionIdQueriesRoute
    }
    '/conn/$connectionId/tables/': {
      id: '/conn/$connectionId/tables/'
      path: '/'
      fullPath: '/conn/$connectionId/tables/'
      preLoaderRoute: typeof ConnConnectionIdTablesIndexRouteImport
      parentRoute: typeof ConnConnectionIdTablesRoute
    }
    '/conn/$connectionId/tables/$tableName/': {
      id: '/conn/$connectionId/tables/$tableName/'
      path: '/$tableName'
      fullPath: '/conn/$connectionId/tables/$tableName/'
      preLoaderRoute: typeof ConnConnectionIdTablesTableNameIndexRouteImport
      parentRoute: typeof ConnConnectionIdTablesRoute
    }
  }
}

interface ConnConnectionIdQueriesRouteChildren {
  ConnConnectionIdQueriesIndexRoute: typeof ConnConnectionIdQueriesIndexRoute
}

const ConnConnectionIdQueriesRouteChildren: ConnConnectionIdQueriesRouteChildren =
  {
    ConnConnectionIdQueriesIndexRoute: ConnConnectionIdQueriesIndexRoute,
  }

const ConnConnectionIdQueriesRouteWithChildren =
  ConnConnectionIdQueriesRoute._addFileChildren(
    ConnConnectionIdQueriesRouteChildren,
  )

interface ConnConnectionIdTablesRouteChildren {
  ConnConnectionIdTablesIndexRoute: typeof ConnConnectionIdTablesIndexRoute
  ConnConnectionIdTablesTableNameIndexRoute: typeof ConnConnectionIdTablesTableNameIndexRoute
}

const ConnConnectionIdTablesRouteChildren: ConnConnectionIdTablesRouteChildren =
  {
    ConnConnectionIdTablesIndexRoute: ConnConnectionIdTablesIndexRoute,
    ConnConnectionIdTablesTableNameIndexRoute:
      ConnConnectionIdTablesTableNameIndexRoute,
  }

const ConnConnectionIdTablesRouteWithChildren =
  ConnConnectionIdTablesRoute._addFileChildren(
    ConnConnectionIdTablesRouteChildren,
  )

interface ConnConnectionIdRouteChildren {
  ConnConnectionIdQueriesRoute: typeof ConnConnectionIdQueriesRouteWithChildren
  ConnConnectionIdTablesRoute: typeof ConnConnectionIdTablesRouteWithChildren
  ConnConnectionIdIndexRoute: typeof ConnConnectionIdIndexRoute
}

const ConnConnectionIdRouteChildren: ConnConnectionIdRouteChildren = {
  ConnConnectionIdQueriesRoute: ConnConnectionIdQueriesRouteWithChildren,
  ConnConnectionIdTablesRoute: ConnConnectionIdTablesRouteWithChildren,
  ConnConnectionIdIndexRoute: ConnConnectionIdIndexRoute,
}

const ConnConnectionIdRouteWithChildren =
  ConnConnectionIdRoute._addFileChildren(ConnConnectionIdRouteChildren)

interface ConnRouteChildren {
  ConnConnectionIdRoute: typeof ConnConnectionIdRouteWithChildren
  ConnNewRoute: typeof ConnNewRoute
}

const ConnRouteChildren: ConnRouteChildren = {
  ConnConnectionIdRoute: ConnConnectionIdRouteWithChildren,
  ConnNewRoute: ConnNewRoute,
}

const ConnRouteWithChildren = ConnRoute._addFileChildren(ConnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConnRoute: ConnRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
