import * as stylex from '@stylexjs/stylex'

import { layerIndexes } from '../../tokens/layers.stylex'
import {
  borderColors,
  ghostElementColors,
  spatial,
  surfaceColors,
  textColors,
} from '../../tokens/semantics.stylex'
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from '../../tokens/value.stylex'

export const commandStyles = stylex.create({
  surface: {
    borderColor: borderColors.default,
    borderRadius: borderRadii.s,
    borderStyle: 'solid',
    borderWidth: 1,
    overflow: 'hidden',
    backgroundColor: surfaceColors.raised,
    color: textColors.default,
    display: 'flex',
    flexDirection: 'column',
    maxWidth: spatial['content-measure'],
    minWidth: spatial['popup-width-s'],
    width: '100%',
  },
  input: {
    borderWidth: 0,
    outline: 'none',
    paddingInline: spacing.s,
    appearance: 'none',
    backgroundColor: 'transparent',
    borderBlockEndColor: borderColors.subtle,
    borderBlockEndStyle: 'solid',
    borderBlockEndWidth: 1,
    color: textColors.default,
    flexShrink: 0,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.ui,
    paddingInlineEnd: spatial['control-height-xl'],
    height: spatial['control-height-xl'],
    width: '100%',
    '::placeholder': { color: textColors.placeholder },
  },
  inputInRow: {
    paddingInline: 0,
    borderBlockEndWidth: 0,
    flexBasis: 'auto',
    flexGrow: 1,
    flexShrink: 1,
    paddingInlineEnd: spatial['control-height-xl'],
    height: '100%',
    minWidth: spatial['control-height-xl'],
    width: 'auto',
  },
  inputWithoutDivider: { borderBlockEndWidth: 0 },
  inputRow: {
    gap: spacing.xs,
    paddingInline: spacing.s,
    alignItems: 'center',
    borderBlockEndColor: borderColors.subtle,
    borderBlockEndStyle: 'solid',
    borderBlockEndWidth: 1,
    display: 'flex',
    flexShrink: 0,
    height: spatial['control-height-xl'],
    minWidth: 0,
    overflowX: 'auto',
    overflowY: 'hidden',
    overscrollBehaviorX: 'none',
  },
  list: {
    padding: spacing.xxs,
    gap: spacing.xxs,
    outline: 'none',
    display: 'flex',
    flexDirection: 'column',
    maxHeight: spatial['viewport-height-m'],
    minHeight: 0,
    overflowY: 'auto',
  },
  listEmpty: {},
  group: { display: 'flex', flexDirection: 'column' },
  groupLabel: {
    paddingBlock: spacing.xs,
    paddingInline: spacing.s,
    color: textColors.muted,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.compact,
  },
  item: {
    borderRadius: borderRadii.xs,
    gap: spacing.m,
    outline: 'none',
    paddingInline: spacing.s,
    alignItems: 'center',
    backgroundColor: {
      default: 'transparent',
      ':hover': ghostElementColors.hover,
      ':active': ghostElementColors.pressed,
    },
    cursor: 'default',
    display: 'flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.ui,
    userSelect: 'none',
    minHeight: spatial['collection-row-height-l'],
  },
  itemHighlighted: {
    backgroundColor: ghostElementColors.hover,
    outlineColor: { default: 'transparent', '@media (forced-colors: active)': 'Highlight' },
    outlineStyle: 'solid',
    outlineWidth: { default: 0, '@media (forced-colors: active)': 1 },
  },
  itemSelected: { backgroundColor: ghostElementColors.selected },
  itemDisabled: { color: textColors.disabled, cursor: 'not-allowed' },
  itemText: { flex: '1', display: 'flex', flexDirection: 'column', minWidth: 0 },
  itemTextInline: { gap: spacing.s, alignItems: 'baseline', flexDirection: 'row' },
  itemLabel: { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  itemDescription: {
    overflow: 'hidden',
    color: textColors.muted,
    fontSize: fontSizes[1],
    lineHeight: lineHeights.compact,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  empty: {
    padding: { default: spacing.l, ':empty': 0 },
    color: textColors.muted,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
  },
  separator: { backgroundColor: borderColors.subtle, height: 1 },
  footer: {
    gap: spacing.s,
    paddingInline: spacing.s,
    alignItems: 'center',
    borderBlockStartColor: borderColors.subtle,
    borderBlockStartStyle: 'solid',
    borderBlockStartWidth: 1,
    color: textColors.muted,
    display: 'flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    height: spatial['control-height-xl'],
  },
  shortcut: { flexShrink: 0, marginInlineStart: 'auto' },
  key: {
    borderColor: borderColors.subtle,
    borderRadius: borderRadii.xs,
    borderStyle: 'solid',
    borderWidth: 1,
    paddingInline: spacing.xxs,
    backgroundColor: surfaceColors.default,
    color: textColors.muted,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    lineHeight: lineHeights.compact,
  },
  backdrop: {
    inset: 0,
    backgroundColor: surfaceColors.backdrop,
    position: 'fixed',
    zIndex: layerIndexes.modal,
  },
  backdropOpen: {},
  backdropClosed: {},
  backdropStarting: {},
  backdropEnding: {},
  viewport: {
    inset: 0,
    padding: spacing.xl,
    alignItems: 'flex-start',
    display: 'flex',
    justifyContent: 'center',
    position: 'fixed',
    zIndex: layerIndexes.modal,
    overflowY: 'auto',
  },
  viewportOpen: {},
  viewportClosed: {},
  viewportNested: {},
  viewportNestedDialogOpen: {},
  viewportStarting: {},
  viewportEnding: {},
  popup: {
    borderRadius: borderRadii.s,
    outline: 'none',
    overflow: 'hidden',
    marginBlockStart: '12vh',
    position: 'relative',
    maxWidth: spatial['content-measure'],
    width: '100%',
  },
  popupOpen: {},
  popupClosed: {},
  popupNested: {},
  popupNestedDialogOpen: {},
  popupStarting: {},
  popupEnding: {},
  title: {
    margin: -1,
    padding: 0,
    overflow: 'hidden',
    clip: 'rect(0 0 0 0)',
    position: 'absolute',
    whiteSpace: 'nowrap',
    height: 1,
    width: 1,
  },
  close: {
    alignItems: 'center',
    display: 'flex',
    insetBlockStart: 1,
    insetInlineEnd: 1,
    justifyContent: 'center',
    position: 'absolute',
    zIndex: 1,
    height: `calc(${spatial['control-height-xl']} - 2px)`,
    width: spatial['control-height-xl'],
  },
})
