import * as stylex from "@stylexjs/stylex";

import { layerIndexes } from "../../tokens/layers.stylex";
import { backgroundColors, borderColors, textColors } from "../../tokens/semantics.stylex";
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  lineHeights,
  spacing,
} from "../../tokens/value.stylex";

export const comboboxStyles = stylex.create({
  inputGroup: {
    borderColor: {
      default: borderColors.border,
      ":focus-within": borderColors["border-focused"],
    },
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    backgroundColor: backgroundColors["bg-card"],
    display: "flex",
    outlineColor: borderColors["border-focused"],
    outlineOffset: 0,
    minWidth: 200,
  },
  inputGroupFocusVisible: { outlineWidth: 2 },
  inputGroupInvalid: {
    borderColor: borderColors["border-danger"],
    outlineColor: borderColors["border-danger-subtle"],
    outlineWidth: 2,
  },
  inputGroupDisabled: {
    borderColor: borderColors["border-secondary"],
    backgroundColor: backgroundColors["bg-disabled"],
    outlineWidth: 0,
  },
  inputGroupWidthFull: { width: "100%" },
  inputGroupBare: {
    borderColor: { default: "transparent", ":focus-within": "transparent" },
    borderWidth: 0,
    backgroundColor: "transparent",
  },
  input: {
    borderWidth: 0,
    flex: "1",
    outline: "none",
    paddingInline: spacing.xs,
    appearance: "none",
    backgroundColor: "transparent",
    color: textColors["text-default"],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.normal,
    height: 26,
    minWidth: 0,
    "::placeholder": { color: textColors["text-subtle"] },
  },
  inputDisabled: { color: textColors["text-disabled"], cursor: "not-allowed" },
  action: {
    padding: 0,
    borderWidth: 0,
    alignItems: "center",
    appearance: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": backgroundColors["bg-hover"],
      ":active": backgroundColors["bg-pressed"],
    },
    color: textColors["text-muted"],
    cursor: "pointer",
    display: "inline-flex",
    justifyContent: "center",
    height: 26,
    width: 26,
  },
  actionDisabled: {
    backgroundColor: { default: "transparent", ":hover": "transparent", ":active": "transparent" },
    color: textColors["text-disabled"],
    cursor: "not-allowed",
  },
  icon: {
    display: "block",
    transform: "rotate(0deg)",
    transitionDuration: "250ms",
    transitionProperty: "transform",
    height: 14,
    width: 14,
  },
  iconOpen: { transform: "rotate(180deg)" },
  trigger: {
    backgroundColor: {
      default: "transparent",
      ":disabled": backgroundColors["bg-disabled"],
    },
    color: { default: textColors["text-default"], ":disabled": textColors["text-disabled"] },
  },
  triggerWidthContent: { width: "fit-content" },
  triggerWidthS: { maxWidth: 200, width: "100%" },
  triggerWidthM: { maxWidth: 280, width: "100%" },
  triggerWidthFull: { width: "100%" },
  positioner: { outline: "none", zIndex: layerIndexes.popup },
  popup: {
    borderColor: borderColors.border,
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    outline: "none",
    backgroundColor: backgroundColors["bg-popover"],
    color: textColors["text-default"],
    transformOrigin: "var(--transform-origin)",
    maxWidth: "var(--available-width)",
    minWidth: "var(--anchor-width)",
  },
  popupWidthAnchor: { width: "var(--anchor-width)" },
  popupWidthContent: { width: "max-content" },
  popupWidthS: { width: 240 },
  popupWidthM: { width: 320 },
  popupWidthL: { width: 400 },
  popupTransition: { opacity: 0, transform: "scale(0.98)" },
  popupHeader: {
    flexShrink: 0,
    paddingBlock: spacing.xxs,
  },
  popupFooter: {
    flexShrink: 0,
    padding: spacing.xxs,
  },
  viewport: {
    padding: spacing.xxs,
    // paddingBlock: spacing.xs,
    minHeight: 0,
    overflowY: "auto",
  },
  viewportHeightS: { maxHeight: 160 },
  viewportHeightM: { maxHeight: 240 },
  viewportHeightL: { maxHeight: 320 },
  viewportHeightAvailable: { maxHeight: "var(--available-height)" },
  list: {
    gap: spacing.xxs,
    outline: "none",
    overscrollBehavior: "contain",
    display: "flex",
    flexDirection: "column",
    maxHeight: "var(--available-height)",
    overflowY: "auto",
    // paddingBlock: spacing.xxs
  },
  listEmpty: {},
  group: {
    display: "flex",
    flexDirection: "column",
  },
  groupLabel: {
    paddingBlock: spacing.xs,
    paddingInline: spacing.m,
    color: textColors["text-muted"],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    lineHeight: lineHeights.tight,
  },
  item: {
    padding: spacing.xxs,
    borderRadius: borderRadii.xs,
    gap: spacing.m,
    outline: "none",
    alignItems: "center",
    boxSizing: "border-box",
    cursor: "default",
    display: "grid",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    gridTemplateColumns: "minmax(0, 1fr) 16px",
    lineHeight: lineHeights.tight,
    userSelect: "none",
    width: "auto",
  },
  itemInteractive: {
    backgroundColor: {
      default: "transparent",
      ":hover": backgroundColors["bg-hover"],
      ":active": backgroundColors["bg-pressed"],
    },
  },
  itemHighlighted: {
    backgroundColor: backgroundColors["bg-hover"],
  },
  itemSelected: {
    backgroundColor: backgroundColors["bg-selected"],
  },
  itemDisabled: {
    backgroundColor: { default: "transparent", ":hover": "transparent", ":active": "transparent" },
    color: textColors["text-disabled"],
    cursor: "not-allowed",
  },
  indicator: {
    alignItems: "center",
    display: "inline-flex",
    gridColumnStart: "2",
    gridRowStart: "1",
    justifyContent: "center",
    justifySelf: "end",
  },
  itemText: {
    gap: spacing.xxs,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  itemLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  itemDescription: {
    overflow: "hidden",
    color: textColors["text-muted"],
    fontSize: fontSizes[1],
    lineHeight: lineHeights.tight,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  label: {
    color: textColors["text-default"],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.normal,
  },
  separator: {
    backgroundColor: borderColors["border-secondary"],
    height: 1,
  },
  empty: {
    padding: { default: spacing.l, ":empty": 0 },
    color: textColors["text-muted"],
    display: "block",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
  },
  status: {
    padding: { default: spacing.l, ":empty": 0 },
    color: textColors["text-muted"],
    display: "block",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
  },
});
