import * as stylex from "@stylexjs/stylex";

import { layerIndexes } from "../../tokens/layers.stylex";
import {
  backgroundColors,
  borderColors,
  spatial,
  textColors,
} from "../../tokens/semantics.stylex";
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from "../../tokens/value.stylex";
import { comboboxStyleVars } from "./comboboxVars.stylex";

export const comboboxStyles = stylex.create({
  inputGroup: {
    borderColor: {
      default: borderColors.border,
      ":focus-within": borderColors["border-focused"],
    },
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    backgroundColor: backgroundColors["bg-card"],
    display: "flex",
    outlineColor: borderColors["outline"],
    outlineOffset: 0,
    minWidth: spatial["combobox-min-width"],
  },
  inputGroupFocusVisible: { outlineWidth: spatial["focus-ring-width"] },
  inputGroupInvalid: {
    borderColor: borderColors["border-danger"],
    outlineColor: borderColors["border-danger-subtle"],
    outlineWidth: spatial["focus-ring-width"],
  },
  inputGroupDisabled: {
    borderColor: borderColors["border-secondary"],
    backgroundColor: backgroundColors["bg-disabled"],
    outlineWidth: 0,
  },
  inputGroupWidthFull: { width: "100%" },
  inputGroupBare: {
    borderColor: { default: "transparent", ":focus-within": "transparent" },
    borderWidth: 0,
    backgroundColor: "transparent",
  },
  input: {
    borderWidth: 0,
    flex: "1",
    outline: "none",
    paddingInline: spacing.s,
    appearance: "none",
    backgroundColor: "transparent",
    color: textColors["text-default"],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.normal,
    height: spatial["control-inner-height-m"],
    minWidth: 0,
    "::placeholder": { color: textColors["text-subtle"] },
  },
  inputDisabled: { color: textColors["text-disabled"], cursor: "not-allowed" },
  action: {
    padding: 0,
    borderWidth: 0,
    alignItems: "center",
    appearance: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": backgroundColors["bg-hover"],
      ":active": backgroundColors["bg-pressed"],
    },
    color: textColors["text-muted"],
    cursor: "pointer",
    display: "inline-flex",
    justifyContent: "center",
    height: spatial["control-inner-height-m"],
    width: spatial["control-inner-height-m"],
  },
  actionDisabled: {
    backgroundColor: { default: "transparent", ":hover": "transparent", ":active": "transparent" },
    color: textColors["text-disabled"],
    cursor: "not-allowed",
  },
  icon: {
    display: "block",
    transform: "rotate(0deg)",
    transitionDuration: "250ms",
    transitionProperty: "transform",
    height: spatial["icon-size-s"],
    width: spatial["icon-size-s"],
  },
  iconOpen: { transform: "rotate(180deg)" },
  trigger: {
    [comboboxStyleVars.triggerTextColor]: textColors["text-default"],
    paddingInline: spacing.xs,
    backgroundColor: {
      default: "transparent",
      ":disabled": backgroundColors["bg-disabled"],
    },
    color: { default: textColors["text-default"], ":disabled": textColors["text-disabled"] },
  },
  triggerOpen: {
    [comboboxStyleVars.triggerTextColor]: textColors["text-selected"],
    backgroundColor: backgroundColors["bg-selected"],
  },
  triggerWidthContent: { width: "fit-content" },
  triggerWidthS: { maxWidth: spatial["combobox-trigger-width-s"], width: "fit-content" },
  triggerWidthM: { maxWidth: spatial["combobox-trigger-width-m"], width: "fit-content" },
  triggerWidthFull: { width: "100%" },
  positioner: { outline: "none", zIndex: layerIndexes.popup },
  popup: {
    borderColor: borderColors.border,
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    outline: "none",
    backgroundColor: backgroundColors["bg-popover"],
    color: textColors["text-default"],
    display: "flex",
    flexDirection: "column",
    transformOrigin: "var(--transform-origin)",
    maxHeight: "var(--available-height)",
    maxWidth: "var(--available-width)",
    minWidth: "var(--anchor-width)",
  },
  popupWidthAnchor: { width: "var(--anchor-width)" },
  popupWidthContent: { width: "max-content" },
  popupWidthS: { width: spatial["popup-width-s"] },
  popupWidthM: { width: spatial["popup-width-m"] },
  popupWidthL: { width: spatial["popup-width-l"] },
  popupTransition: { opacity: 0, transform: "scale(0.98)" },
  popupSection: {
    padding: spatial["popup-collection-padding"],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.normal,
  },
  popupHeader: {
    flexShrink: 0,
  },
  popupFooter: {
    flexShrink: 0,
  },
  viewport: {
    padding: spatial["popup-collection-padding"],
    minHeight: 0,
    overflowY: "auto",
  },
  viewportHeightS: { maxHeight: spatial["viewport-height-s"] },
  viewportHeightM: { maxHeight: spatial["viewport-height-m"] },
  viewportHeightL: { maxHeight: spatial["viewport-height-l"] },
  viewportHeightAvailable: { maxHeight: "var(--available-height)" },
  list: {
    outline: "none",
    overscrollBehavior: "contain",
    display: "flex",
    flexDirection: "column",
    gap: spacing.xxs,
  },
  listEmpty: {},
  group: {
    display: "flex",
    flexDirection: "column",
  },
  groupLabel: {
    paddingBlock: spatial["popup-collection-padding"],
    paddingInline: spatial["popup-item-inline-padding"],
    color: textColors["text-muted"],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.tight,
  },
  item: {
    borderRadius: borderRadii.xs,
    gap: spacing.m,
    outline: "none",
    paddingInline: spatial["popup-item-inline-padding"],
    alignItems: "center",
    boxSizing: "border-box",
    cursor: "default",
    display: "grid",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.regular,
    gridTemplateColumns: `minmax(0, 1fr) ${spatial["icon-size-m"]}`,
    lineHeight: lineHeights.normal,
    userSelect: "none",
    minHeight: spatial["popup-row-min-height"],
    width: "auto",
  },
  itemInteractive: {
    backgroundColor: {
      default: "transparent",
      ":hover": backgroundColors["bg-hover"],
      ":active": backgroundColors["bg-pressed"],
    },
  },
  itemHighlighted: {
    backgroundColor: backgroundColors["bg-hover"],
  },
  itemSelected: {
    backgroundColor: backgroundColors["bg-selected"],
  },
  itemDisabled: {
    backgroundColor: { default: "transparent", ":hover": "transparent", ":active": "transparent" },
    color: textColors["text-disabled"],
    cursor: "not-allowed",
  },
  indicator: {
    alignItems: "center",
    display: "inline-flex",
    gridColumnStart: "2",
    gridRowStart: "1",
    justifyContent: "center",
    justifySelf: "end",
  },
  itemText: {
    gap: spacing.xxs,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  itemLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  itemDescription: {
    overflow: "hidden",
    color: textColors["text-muted"],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.tight,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  label: {
    color: textColors["text-default"],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.normal,
  },
  separator: {
    backgroundColor: borderColors["border-secondary"],
    height: 1,
  },
  empty: {
    padding: { default: spacing.l, ":empty": 0 },
    color: textColors["text-muted"],
    display: "block",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
  },
  status: {
    padding: { default: spacing.l, ":empty": 0 },
    color: textColors["text-muted"],
    display: "block",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
  },
});
