import * as stylex from "@stylexjs/stylex";

import { layerIndexes } from "../../tokens/layers.stylex";
import { backgroundColors, borderColors, textColors } from "../../tokens/semantics.stylex";
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  lineHeights,
  spacing,
} from "../../tokens/value.stylex";

export const comboboxStyles = stylex.create({
  inputGroup: {
    borderRadius: borderRadii.xs,
    backgroundColor: backgroundColors["bg-secondary"],
    display: "flex",
    minWidth: 200,
  },
  inputGroupInvalid: { borderColor: borderColors["border-danger"] },
  inputGroupDisabled: { backgroundColor: backgroundColors["bg-disabled"] },
  inputGroupFullWidth: { width: "100%" },
  input: {
    borderWidth: 0,
    flex: "1",
    outline: "none",
    paddingInline: spacing.m,
    appearance: "none",
    backgroundColor: "transparent",
    color: textColors["text-default"],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.normal,
    height: 26,
    minWidth: 0,
    "::placeholder": { color: textColors["text-subtle"] },
  },
  inputDisabled: { color: textColors["text-disabled"], cursor: "not-allowed" },
  action: {
    padding: 0,
    borderWidth: 0,
    alignItems: "center",
    appearance: "none",
    backgroundColor: { default: "transparent", ":hover": backgroundColors["bg-hover"] },
    color: textColors["text-muted"],
    cursor: "pointer",
    display: "inline-flex",
    justifyContent: "center",
    height: 26,
    width: 26,
  },
  actionDisabled: { color: textColors["text-disabled"], cursor: "not-allowed" },
  icon: { display: "block", height: 14, width: 14 },
  positioner: { outline: "none", zIndex: layerIndexes.popup },
  popup: {
    borderColor: borderColors.border,
    borderRadius: borderRadii.s,
    borderStyle: "solid",
    borderWidth: 1,
    outline: "none",
    backgroundColor: backgroundColors["bg-card"],
    color: textColors["text-default"],
    transformOrigin: "var(--transform-origin)",
    maxWidth: "var(--available-width)",
    minWidth: "var(--anchor-width)",
  },
  popupWidthAnchor: { width: "var(--anchor-width)" },
  popupWidthContent: { width: "max-content" },
  popupWidthS: { width: 240 },
  popupWidthM: { width: 320 },
  popupWidthL: { width: 400 },
  popupTransition: { opacity: 0, transform: "scale(0.98)" },
  popupHeader: {
    flexShrink: 0,
    padding: spacing.xs,
  },
  popupFooter: {
    flexShrink: 0,
    padding: spacing.xs,
  },
  viewport: {
    padding: spacing.xs,
    minHeight: 0,
    overflowY: "auto",
  },
  viewportHeightS: { maxHeight: 160 },
  viewportHeightM: { maxHeight: 240 },
  viewportHeightL: { maxHeight: 320 },
  viewportHeightAvailable: { maxHeight: "var(--available-height)" },
  list: {
    outline: "none",
    overscrollBehavior: "contain",
    paddingBlock: spacing.xs,
    maxHeight: "var(--available-height)",
    overflowY: "auto",
  },
  listEmpty: { paddingBlock: 0 },
  item: {
    padding: spacing.xs,
    borderRadius: borderRadii.xs,
    gap: spacing.m,
    outline: "none",
    paddingInline: spacing.m,
    alignItems: "center",
    boxSizing: "border-box",
    cursor: "default",
    display: "grid",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    gridTemplateColumns: "minmax(0, 1fr) 16px",
    lineHeight: lineHeights.tight,
    userSelect: "none",
    width: "100%",
  },
  itemHighlighted: {
    backgroundColor: backgroundColors["bg-secondary"],
  },
  itemDisabled: { color: textColors["text-disabled"] },
  indicator: {
    alignItems: "center",
    display: "inline-flex",
    gridColumnStart: "2",
    gridRowStart: "1",
    justifyContent: "center",
    justifySelf: "end",
  },
  itemText: {
    gap: spacing.xxs,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  itemLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  itemDescription: {
    overflow: "hidden",
    color: textColors["text-muted"],
    fontSize: fontSizes[1],
    lineHeight: lineHeights.tight,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  label: {
    color: textColors["text-default"],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.normal,
  },
  separator: {
    backgroundColor: borderColors["border-secondary"],
    height: 1,
  },
  empty: {
    padding: spacing.l,
    color: textColors["text-muted"],
    display: "block",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
  },
  status: {
    padding: spacing.l,
    color: textColors["text-muted"],
    display: "block",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
  },
});
