import * as stylex from '@stylexjs/stylex'

import { borderColors, spatial, surfaceColors } from '../../tokens/semantics.stylex'
import { layerIndexes } from '../../tokens/layers.stylex'
import {
  borderRadii,
  dimensions,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from '../../tokens/value.stylex'
import { workspaceTabsColors } from './workspaceTabsColors.stylex'
import { workspaceTabsVars } from './workspaceTabsVars.stylex'

export const workspaceTabsStyles = stylex.create({
  root: {
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    width: '100%',
  },
  rootHorizontal: {},
  rootVertical: {},
  rootActivationLeft: {},
  rootActivationRight: {},
  rootActivationUp: {},
  rootActivationDown: {},
  rootActivationNone: {},
  bar: {
    overflow: 'hidden',
    alignItems: 'center',
    display: 'flex',
    position: 'relative',
    minWidth: 0,
    width: '100%',
  },
  fixedArea: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: surfaceColors.background,
    display: 'flex',
    flexShrink: 0,
    position: 'relative',
    zIndex: layerIndexes.navigation,
  },
  leadingArea: {
    paddingRight: spacing.xs,
    '::after': {
      backgroundColor: borderColors.subtle,
      content: '',
      pointerEvents: 'none',
      position: 'absolute',
      height: spatial['control-height-xs'],
      right: 0,
      width: 1,
    },
  },
  trailingArea: {
    paddingLeft: spacing.xs,
    '::before': {
      backgroundColor: borderColors.subtle,
      content: '',
      pointerEvents: 'none',
      position: 'absolute',
      height: spatial['control-height-xs'],
      left: 0,
      width: 1,
    },
  },
  list: {
    gap: spacing.xs,
    marginInline: spacing.xs,
    alignItems: 'center',
    display: 'flex',
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
    overflowX: 'auto',
    overflowY: 'clip',
    overscrollBehaviorX: 'none',
    width: 'auto',
  },
  listHorizontal: {},
  listVertical: {},
  listActivationLeft: {},
  listActivationRight: {},
  listActivationUp: {},
  listActivationDown: {},
  listActivationNone: {},
  item: {
    borderRadius: borderRadii.xs,
    [workspaceTabsVars.background]: {
      default: workspaceTabsColors.background,
      ':focus-within': workspaceTabsColors.hoverBackground,
      ':hover': workspaceTabsColors.hoverBackground,
    },
    [workspaceTabsVars.tabTextColor]: {
      default: workspaceTabsColors.text,
      ':focus-within': workspaceTabsColors.hoverText,
      ':hover': workspaceTabsColors.hoverText,
    },
    overflow: 'hidden',
    alignItems: 'center',
    backgroundColor: workspaceTabsVars.background,
    display: 'flex',
    flexShrink: 0,
    position: 'relative',
    height: spatial['tab-height'],
    width: dimensions[160],
    '::after': {
      inset: `calc(${spatial['focus-ring-width']} / 2)`,
      borderColor: workspaceTabsColors.focusRing,
      borderRadius: 'inherit',
      borderStyle: {
        default: 'none',
        ':has([data-slot="workspace-tabs-tab"]:focus-visible)': 'solid',
      },
      borderWidth: spatial['focus-ring-width'],
      content: '',
      pointerEvents: 'none',
      position: 'absolute',
      zIndex: 2,
    },
  },
  itemClosable: {
    [workspaceTabsVars.closeOpacity]: {
      default: 0,
      ':focus-within': 1,
      ':hover': 1,
    },
    [workspaceTabsVars.closePointerEvents]: {
      default: 'none',
      ':focus-within': 'auto',
      ':hover': 'auto',
    },
  },
  itemActive: {
    [workspaceTabsVars.background]: workspaceTabsColors.selectedBackground,
  },
  itemDragging: {
    [workspaceTabsVars.background]: workspaceTabsColors.hoverBackground,
  },
  itemDisabled: {
    [workspaceTabsVars.background]: workspaceTabsColors.disabledBackground,
    [workspaceTabsVars.closeOpacity]: 0,
    [workspaceTabsVars.closePointerEvents]: 'none',
    opacity: 0.6,
  },
  tab: {
    borderRadius: borderRadii.xs,
    borderStyle: 'none',
    gap: spacing.xs,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: workspaceTabsColors.buttonBackground,
    color: workspaceTabsVars.tabTextColor,
    cursor: 'pointer',
    display: 'flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.regular,
    justifyContent: 'flex-start',
    lineHeight: lineHeights.ui,
    outlineStyle: 'none',
    textAlign: 'start',
    userSelect: 'none',
    height: '100%',
    minWidth: 0,
    paddingLeft: spacing.xs,
    width: '100%',
  },
  tabActive: {
    color: workspaceTabsColors.selectedText,
  },
  tabClosable: {
    paddingRight: spacing.xs,
  },
  tabDisabled: {
    color: workspaceTabsColors.disabledText,
    cursor: 'not-allowed',
  },
  tabHorizontal: {},
  tabVertical: {},
  tabActivationLeft: {},
  tabActivationRight: {},
  tabActivationUp: {},
  tabActivationDown: {},
  tabActivationNone: {},
  prefix: {
    alignItems: 'center',
    display: 'flex',
    flexShrink: 0,
    justifyContent: 'center',
    height: spatial['icon-size-m'],
    width: spatial['icon-size-m'],
  },
  title: {
    overflow: 'hidden',
    display: 'block',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  titleReplaceable: {
    fontStyle: 'italic',
  },
  closeContainer: {
    alignItems: 'center',
    backgroundImage: `linear-gradient(to right, transparent 0, ${workspaceTabsVars.background} ${spacing.l}, ${workspaceTabsVars.background} 100%), linear-gradient(to right, transparent 0, ${workspaceTabsColors.closeBackdrop} ${spacing.l}, ${workspaceTabsColors.closeBackdrop} 100%)`,
    display: 'flex',
    insetInlineEnd: spacing.xxs,
    justifyContent: 'flex-end',
    opacity: workspaceTabsVars.closeOpacity,
    pointerEvents: 'none',
    position: 'absolute',
    transform: 'translateY(-50%)',
    zIndex: 1,
    height: spatial['control-height-xs'],
    top: '50%',
    width: `calc(${spatial['control-height-xs']} + ${spacing.l})`,
  },
  closeAction: {
    [workspaceTabsVars.closeIconColor]: {
      default: workspaceTabsColors.closeIcon,
      ':focus-visible': workspaceTabsColors.closeIconHover,
      ':hover': workspaceTabsColors.closeIconHover,
    },
    outlineOffset: {
      default: 0,
      ':focus-visible': 0,
    },
    pointerEvents: workspaceTabsVars.closePointerEvents,
    zIndex: 1,
    '::before': {
      insetBlock: `calc((${spatial['control-height-xs']} - ${spatial['tab-height']}) / 2)`,
      insetInline: `calc((${spatial['control-height-xs']} - ${spatial['interaction-target-min']}) / 2)`,
      content: '',
      position: 'absolute',
    },
  },
  closeIcon: {
    color: workspaceTabsVars.closeIconColor,
    display: 'block',
    position: 'relative',
    zIndex: 1,
    height: spatial['icon-size-s'],
    width: spatial['icon-size-s'],
  },
  panel: {
    overflow: 'hidden',
    flexGrow: 1,
    outlineColor: workspaceTabsColors.focusRing,
    outlineOffset: -2,
    outlineStyle: {
      default: 'none',
      ':focus-visible': 'solid',
    },
    outlineWidth: spatial['focus-ring-width'],
    minHeight: 0,
    minWidth: 0,
    width: '100%',
  },
  panelHidden: {},
  panelIndexed: {},
  panelHorizontal: {},
  panelVertical: {},
  panelActivationLeft: {},
  panelActivationRight: {},
  panelActivationUp: {},
  panelActivationDown: {},
  panelActivationNone: {},
  panelStarting: {},
  panelEnding: {},
})
