import * as stylex from '@stylexjs/stylex'

import {
  backgroundColors,
  borderColors,
  spatial,
  textColors,
} from '../../tokens/semantics.stylex'
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from '../../tokens/value.stylex'

const reducedMotion = '@media (prefers-reduced-motion: reduce)'

export const segmentedControlStyles = stylex.create({
  root: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    width: '100%',
  },
  list: {
    padding: spacing.xxs,
    borderRadius: borderRadii.s,
    gap: spacing.xxs,
    alignItems: 'stretch',
    backgroundColor: backgroundColors['bg-subtle'],
    boxSizing: 'border-box',
    display: 'inline-flex',
    isolation: 'isolate',
    position: 'relative',
    height: spatial['control-height-m'],
    width: 'fit-content',
  },
  listFullWidth: {
    display: 'flex',
    width: '100%',
  },
  item: {
    borderColor: 'transparent',
    borderRadius: borderRadii.xs,
    borderStyle: 'solid',
    borderWidth: 1,
    paddingInline: spacing.m,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: 'transparent',
    color: {
      default: textColors['text-muted'],
      ':hover': textColors['text-secondary'],
    },
    cursor: 'pointer',
    display: 'inline-flex',
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.regular,
    justifyContent: 'center',
    lineHeight: lineHeights.none,
    outlineColor: borderColors['border-focused'],
    outlineOffset: 1,
    outlineStyle: {
      default: 'none',
      ':focus-visible': 'solid',
    },
    outlineWidth: spatial['focus-ring-width'],
    position: 'relative',
    userSelect: 'none',
    whiteSpace: 'nowrap',
    zIndex: 1,
    minWidth: 0,
  },
  itemActive: {
    color: textColors['text-default'],
  },
  itemDisabled: {
    color: textColors['text-disabled'],
    cursor: 'not-allowed',
  },
  indicator: {
    borderColor: borderColors['border'],
    borderRadius: borderRadii.xs,
    borderStyle: 'solid',
    borderWidth: 1,
    backgroundColor: backgroundColors['bg-popover'],
    boxSizing: 'border-box',
    pointerEvents: 'none',
    position: 'absolute',
    transform: 'translate(var(--active-tab-left), var(--active-tab-top))',
    transitionDuration: { default: '140ms', [reducedMotion]: '0ms' },
    transitionProperty: 'transform, width',
    transitionTimingFunction: 'cubic-bezier(0.77, 0, 0.175, 1)',
    zIndex: 0,
    height: 'var(--active-tab-height)',
    left: 0,
    top: 0,
    width: 'var(--active-tab-width)',
  },
  indicatorInstant: {
    transitionDuration: '0ms',
  },
  panel: {
    outlineColor: borderColors['border-focused'],
    outlineOffset: -2,
    outlineStyle: {
      default: 'none',
      ':focus-visible': 'solid',
    },
    outlineWidth: spatial['focus-ring-width'],
    minHeight: 0,
    minWidth: 0,
  },
})
