import * as stylex from '@stylexjs/stylex'

import { layerIndexes } from '../../tokens/layers.stylex'
import { spatial, surfaceColors, textColors } from '../../tokens/semantics.stylex'
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  lineHeights,
  spacing,
} from '../../tokens/value.stylex'

const reducedMotion = '@media (prefers-reduced-motion: reduce)'

export const tooltipStyles = stylex.create({
  trigger: {
    padding: 0,
    borderStyle: 'none',
    appearance: 'none',
    backgroundColor: 'transparent',
    color: 'inherit',
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: 'inherit',
    lineHeight: 'inherit',
  },
  triggerOpen: {},
  triggerDisabled: {},
  positioner: {
    outline: 'none',
    zIndex: layerIndexes.tooltip,
    maxWidth: 'var(--available-width)',
  },
  positionerOpen: {},
  positionerClosed: {},
  positionerAnchorHidden: {},
  positionerInstant: {},
  positionerSideTop: {},
  positionerSideBottom: {},
  positionerSideLeft: {},
  positionerSideRight: {},
  positionerSideInlineStart: {},
  positionerSideInlineEnd: {},
  positionerAlignStart: {},
  positionerAlignCenter: {},
  positionerAlignEnd: {},
  popup: {
    borderRadius: borderRadii.xs,
    paddingBlock: spacing.xxs,
    paddingInline: spacing.s,
    backgroundColor: surfaceColors.inverse,
    color: textColors.onInverse,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    lineHeight: lineHeights.compact,
    overflowWrap: 'anywhere',
    transformOrigin: 'var(--transform-origin)',
    transitionDuration: { default: '100ms', [reducedMotion]: '0ms' },
    transitionProperty: 'opacity, transform',
    transitionTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
    maxWidth: spatial['popup-width-m'],
  },
  popupTransition: {
    opacity: 0,
    transform: 'scale(0.98)',
  },
  popupOpen: {},
  popupClosed: {},
  popupStarting: {},
  popupEnding: {},
  popupInstant: {},
  popupSideTop: {},
  popupSideBottom: {},
  popupSideLeft: {},
  popupSideRight: {},
  popupSideInlineStart: {},
  popupSideInlineEnd: {},
  popupAlignStart: {},
  popupAlignCenter: {},
  popupAlignEnd: {},
})
