import * as stylex from "@stylexjs/stylex";

import { interactiveControlVars } from "../../primitives/interactiveControlVars.stylex";
import {
  borderColors,
  elementColors,
  focusColors,
  surfaceColors,
  textColors,
  spatial,
} from "../../tokens/semantics.stylex";
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from "../../tokens/value.stylex";

export const checkboxStyles = stylex.create({
  label: {
    [interactiveControlVars.hoverBorderColor]: {
      default: borderColors.default,
      ":hover": borderColors.strong,
    },
    gap: spacing.s,
    alignItems: "center",
    color: textColors.default,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.compact,
    userSelect: "none",
  },
  labelRow: {
    boxSizing: "border-box",
    paddingLeft: spacing.m,
    paddingRight: spacing.m,
    width: "100%",
  },
  root: {
    margin: 0,
    padding: 0,
    borderColor: {
      default: borderColors.default,
      ":focus-visible": borderColors.focused,
    },
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    alignItems: "center",
    appearance: "none",
    backgroundColor: surfaceColors.default,
    color: "transparent",
    cursor: "pointer",
    display: "inline-flex",
    flexShrink: 0,
    justifyContent: "center",
    outlineColor: focusColors.ring,
    outlineOffset: 2,
    outlineStyle: "solid",
    outlineWidth: {
      default: 0,
      ":focus-visible": spatial["focus-ring-width"],
    },
    position: "relative",
    "::before": {
      content: "",
      position: "absolute",
      transform: "translate(-50%, -50%)",
      height: spatial["interaction-target-min"],
      left: "50%",
      top: "50%",
      width: spatial["interaction-target-min"],
    },
  },
  hoverable: {
    borderColor: {
      default: interactiveControlVars.hoverBorderColor,
      ":hover": borderColors.strong,
    },
  },
  sizeS: {
    height: spatial["icon-size-s"],
    width: spatial["icon-size-s"],
  },
  sizeM: {
    height: spatial["icon-size-m"],
    width: spatial["icon-size-m"],
  },
  selected: {
    borderColor: surfaceColors.inverse,
    backgroundColor: surfaceColors.inverse,
    color: textColors.onInverse,
  },
  invalid: {
    borderColor: borderColors.danger,
  },
  disabled: {
    borderColor: borderColors.subtle,
    backgroundColor: elementColors.disabled,
    color: textColors.disabled,
    cursor: "not-allowed",
  },
  selectedDisabled: {
    borderColor: borderColors.subtle,
  },
  readOnly: {
    cursor: "default",
  },
  rootChecked: {},
  rootUnchecked: {},
  rootIndeterminate: {},
  rootDisabled: {},
  rootReadOnly: {},
  rootRequired: {},
  rootValid: {},
  rootInvalid: {},
  rootTouched: {},
  rootDirty: {},
  rootFilled: {},
  rootFocused: {},
  indicator: {
    alignItems: "center",
    display: "inline-flex",
    justifyContent: "center",
    height: "100%",
    width: "100%",
  },
  indicatorChecked: {},
  indicatorUnchecked: {},
  indicatorIndeterminate: {},
  indicatorDisabled: {},
  indicatorReadOnly: {},
  indicatorRequired: {},
  indicatorValid: {},
  indicatorInvalid: {},
  indicatorTouched: {},
  indicatorDirty: {},
  indicatorFilled: {},
  indicatorFocused: {},
  indicatorStarting: {},
  indicatorEnding: {},
  icon: {
    display: "block",
    height: "100%",
    width: "100%",
  },
});
