import * as stylex from '@stylexjs/stylex'

import {
  backgroundColors,
  borderColors,
  spatial,
  textColors,
} from '../../tokens/semantics.stylex'
import {
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from '../../tokens/value.stylex'

export const dataTableStyles = stylex.create({
  root: {
    backgroundColor: backgroundColors['bg-page'],
    color: textColors['text-default'],
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    width: '100%',
  },
  viewport: {
    overflow: 'auto',
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    minWidth: 0,
    width: '100%',
  },
  table: {
    borderCollapse: 'separate',
    borderSpacing: 0,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    lineHeight: lineHeights.normal,
    tableLayout: 'fixed',
    minWidth: '100%',
    width: 'max-content',
  },
  header: {
    position: 'relative',
    zIndex: 1,
  },
  headerCell: {
    backgroundColor: backgroundColors['bg-table-header'],
    color: textColors['text-secondary'],
    borderBottomColor: borderColors['border-table-header-cell'],
    borderBottomStyle: 'solid',
    overflow: 'hidden',
    borderBottomWidth: 1,
    fontWeight: fontWeights.regular,
    borderRightColor: {
      default: borderColors['border-table-cell'],
      ':has([data-slot="data-table-resize-handle"]:hover)': 'transparent',
      ':has([data-resizing])': 'transparent',
    },
    outlineColor: {
      default: 'transparent',
      ':focus-visible': borderColors['border-focused'],
    },
    outlineOffset: -2,
    borderRightStyle: 'solid',
    outlineStyle: 'solid',
    borderRightWidth: 1,
    outlineWidth: {
      default: 0,
      ':focus-visible': spatial['focus-ring-width'],
    },
    height: spatial['control-height-l'],
    position: 'sticky',
    textAlign: 'start',
    // paddingLeft: spacing.m,
    textOverflow: 'ellipsis',
    paddingBottom: 0,
    // paddingRight: spacing.m,
    whiteSpace: 'nowrap',
    zIndex: 2,
    paddingTop: 0,
    top: 0,
  },
  headerCellActive: {
    backgroundColor: backgroundColors['bg-table-header-cell-active'],
    color: textColors['text-default'],
    borderBottomColor: borderColors['border-table-column-active'],
  },
  headerCellLayout: {
    paddingLeft: 0,
    paddingRight: 0,
  },
  headerCellReorderable: {
    cursor: 'grab',
    touchAction: 'none',
  },
  headerCellDragging: {
    backgroundColor: 'transparent',
    cursor: 'grabbing',
    zIndex: 4,
  },
  headerDragContent: {
    alignItems: 'center',
    boxSizing: 'border-box',
    display: 'flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.regular,
    height: '100%',
    lineHeight: lineHeights.normal,
    overflow: 'hidden',
    paddingLeft: spacing.m,
    paddingRight: spacing.m,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    width: '100%',
  },
  headerDragSource: {
    backgroundColor: 'inherit',
    color: 'inherit',
  },
  headerDragSourceDragging: {
    visibility: 'hidden',
  },
  compactHeaderDragContent: {
    paddingLeft: spacing.s,
    paddingRight: spacing.s,
  },
  columnDragOverlay: {
    boxSizing: 'border-box',
    pointerEvents: 'none',
    position: 'fixed',
  },
  columnDragOverlayContent: {
    backgroundColor: backgroundColors['bg-table-header-cell-active'],
    borderBottomColor: borderColors['border-table-column-active'],
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    color: textColors['text-default'],
  },
  row: {
    backgroundColor: backgroundColors['bg-page'],
  },
  rowSelected: {
    backgroundColor: 'transparent',
  },
  cell: {
    backgroundColor: 'transparent',
    borderBottomColor: borderColors['border-table-cell'],
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    overflow: 'hidden',
    borderRightColor: borderColors['border-table-cell'],
    outlineColor: {
      default: 'transparent',
      ':focus-visible': borderColors['border-focused'],
    },
    outlineOffset: -2,
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    outlineStyle: 'solid',
    height: spatial['control-height-l'],
    outlineWidth: {
      default: 0,
      ':focus-visible': spatial['focus-ring-width'],
    },
    textOverflow: 'ellipsis',
    paddingBottom: 0,
    whiteSpace: 'nowrap',
    paddingLeft: spacing.m,
    paddingRight: spacing.m,
    paddingTop: 0,
  },
  cellColumnActive: {
    backgroundColor: backgroundColors['bg-table-column-cell-active'],
  },
  cellSelected: {
    backgroundColor: backgroundColors['bg-table-row-cell-selected'],
  },
  cellRowActive: {
    backgroundColor: backgroundColors['bg-table-row-cell-active'],
  },
  cellActive: {
    backgroundColor: backgroundColors['bg-table-cell-active'],
    boxShadow: `inset 0 0 0 ${spatial['focus-ring-width']} ${borderColors['border-table-cell-active']}`,
  },
  resizeHandle: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    boxShadow: {
      default: 'none',
      ':hover': `inset -1px 0 0 ${borderColors['border-table-column-active']}`,
    },
    cursor: 'col-resize',
    height: '100%',
    padding: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    touchAction: 'none',
    width: spacing.s,
    zIndex: 3,
  },
  resizeHandleActive: {
    boxShadow: `inset -1px 0 0 ${borderColors['border-table-column-active']}`,
  },
  resizeHandleDragging: {
    visibility: 'hidden',
  },
  compactCell: {
    height: spatial['control-height-m'],
    paddingLeft: spacing.s,
    paddingRight: spacing.s,
  },
  messageCell: {
    padding: spacing.xl,
    color: textColors['text-muted'],
    textAlign: 'center',
    height: spatial['viewport-height-s'],
  },
  expandedCell: {
    padding: spacing.l,
    backgroundColor: backgroundColors['bg-subtle'],
    borderBottomColor: borderColors.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  footer: {
    alignItems: 'center',
    backgroundColor: backgroundColors['bg-page'],
    color: textColors['text-muted'],
    display: 'flex',
    flexShrink: 0,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    borderTopColor: borderColors['border-secondary'],
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    justifyContent: 'space-between',
    minHeight: spatial['control-height-l'],
    paddingLeft: spacing.l,
    paddingRight: spacing.l,
  },
})
