import * as stylex from '@stylexjs/stylex'

import { layerIndexes } from '../../tokens/layers.stylex'
import { focusColors, spatial, surfaceColors, textColors } from '../../tokens/semantics.stylex'
import { borderRadii, shadows } from '../../tokens/value.stylex'

export const multiSelectStyles = stylex.create({
  triggerOpen: {},
  triggerPressed: {},
  triggerDisabled: {},
  positioner: { outline: 'none', zIndex: layerIndexes.popup },
  positionerOpen: {},
  positionerClosed: {},
  positionerAnchorHidden: {},
  positionerInstant: {},
  positionerSideTop: {},
  positionerSideBottom: {},
  positionerSideLeft: {},
  positionerSideRight: {},
  positionerSideInlineStart: {},
  positionerSideInlineEnd: {},
  positionerAlignStart: {},
  positionerAlignCenter: {},
  positionerAlignEnd: {},
  popup: {
    borderRadius: borderRadii.xs,
    backgroundColor: surfaceColors.raised,
    boxShadow: shadows.medium,
    color: textColors.default,
    display: 'flex',
    flexDirection: 'column',
    outlineColor: focusColors.ring,
    outlineOffset: 1,
    outlineStyle: 'solid',
    outlineWidth: { default: 0, ':focus-visible': spatial['focus-ring-width'] },
    transformOrigin: 'var(--transform-origin)',
    maxHeight: 'var(--available-height)',
    maxWidth: 'var(--available-width)',
  },
  popupOpen: {},
  popupClosed: {},
  popupStarting: {},
  popupEnding: {},
  popupInstant: {},
  popupSideTop: {},
  popupSideBottom: {},
  popupSideLeft: {},
  popupSideRight: {},
  popupSideInlineStart: {},
  popupSideInlineEnd: {},
  popupAlignStart: {},
  popupAlignCenter: {},
  popupAlignEnd: {},
  popupWidthS: { width: spatial['multi-select-width-s'] },
  popupWidthM: { width: spatial['multi-select-width-m'] },
  popupWidthL: { width: spatial['multi-select-width-l'] },
})
