export const switchPropNames = [
  "size",
  "checked",
  "defaultChecked",
  "onCheckedChange",
  "name",
  "value",
  "form",
  "uncheckedValue",
  "disabled",
  "readOnly",
  "required",
  "nativeButton",
  "inputRef",
  "render",
] as const;
