import * as stylex from "@stylexjs/stylex";

import { layerIndexes } from "../../tokens/layers.stylex";
import {
  backgroundColors,
  borderColors,
  spatial,
  textColors,
} from "../../tokens/semantics.stylex";
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from "../../tokens/value.stylex";

export const selectStyles = stylex.create({
  label: {
    color: textColors["text-default"],
    cursor: "default",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.compact,
  },
  labelDisabled: { color: textColors["text-disabled"] },
  labelValid: {},
  labelInvalid: {},
  labelTouched: {},
  labelDirty: {},
  labelFilled: {},
  labelFocused: {},
  trigger: {
    borderColor: {
      default: borderColors.border,
      ":focus-visible": borderColors["border-focused"],
    },
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    gap: spacing.l,
    alignItems: "center",
    appearance: "none",
    backgroundColor: {
      default: backgroundColors["bg-card"],
      ":hover": backgroundColors["bg-hover"],
      ":active": backgroundColors["bg-pressed"],
    },
    color: textColors["text-default"],
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    justifyContent: "space-between",
    lineHeight: lineHeights.ui,
    outlineColor: borderColors["outline"],
    outlineOffset: -1,
    outlineStyle: "solid",
    outlineWidth: 0,
    userSelect: "none",
    whiteSpace: "nowrap",
    minWidth: spatial["select-min-width"],
  },
  sizeS: { height: spatial["control-height-s"], paddingInline: spacing.s },
  sizeM: { height: spatial["control-height-m"], paddingInline: spacing.m },
  sizeL: { height: spatial["control-height-l"], paddingInline: spacing.l },
  triggerWidthContent: { width: "max-content" },
  triggerWidthFull: { width: "100%" },
  triggerOpen: { backgroundColor: backgroundColors["bg-selected"] },
  triggerPressed: {},
  triggerReadOnly: {},
  triggerValid: {},
  triggerTouched: {},
  triggerDirty: {},
  triggerFilled: {},
  triggerFocused: {},
  triggerPlaceholder: {},
  triggerSideTop: {},
  triggerSideBottom: {},
  triggerSideLeft: {},
  triggerSideRight: {},
  triggerSideInlineStart: {},
  triggerSideInlineEnd: {},
  triggerInvalid: {
    borderColor: {
      default: borderColors["border-danger"],
      ":focus-visible": borderColors["border-danger"],
    },
    outlineColor: borderColors["border-danger-subtle"],
    outlineOffset: 0,
    outlineStyle: "solid",
    outlineWidth: spatial["focus-ring-width"],
  },
  disabled: {
    borderColor: borderColors.border,
    backgroundColor: {
      default: backgroundColors["bg-card"],
      ":hover": backgroundColors["bg-card"],
      ":active": backgroundColors["bg-card"],
    },
    color: textColors["text-disabled"],
    cursor: "not-allowed",
    outlineWidth: 0,
  },
  valuePlaceholder: { color: textColors["text-muted"] },
  adornment: { alignItems: "center", display: "inline-flex", flexShrink: 0 },
  iconContainer: { alignItems: "center", display: "inline-flex", flexShrink: 0 },
  iconOpen: {},
  icon: {
    display: "block",
    height: spatial["icon-size-s"],
    width: spatial["icon-size-s"],
  },
  positioner: { outline: "none", userSelect: "none", zIndex: layerIndexes.popup },
  positionerOpen: {},
  positionerClosed: {},
  positionerSideNone: {},
  positionerSideTop: {},
  positionerSideBottom: {},
  positionerSideLeft: {},
  positionerSideRight: {},
  positionerSideInlineStart: {},
  positionerSideInlineEnd: {},
  positionerAlignStart: {},
  positionerAlignCenter: {},
  positionerAlignEnd: {},
  positionerAnchorHidden: {},
  popup: {
    borderColor: borderColors.border,
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    outline: "none",
    backgroundColor: backgroundColors["bg-popover"],
    color: textColors["text-default"],
    transformOrigin: "var(--transform-origin)",
    minWidth: "var(--anchor-width)",
  },
  popupTransition: { opacity: 0, transform: "scale(0.98)" },
  popupOpen: {},
  popupClosed: {},
  popupStarting: {},
  popupEnding: {},
  popupSideNone: {},
  popupSideTop: {},
  popupSideBottom: {},
  popupSideLeft: {},
  popupSideRight: {},
  popupSideInlineStart: {},
  popupSideInlineEnd: {},
  popupAlignStart: {},
  popupAlignCenter: {},
  popupAlignEnd: {},
  list: {
    padding: spatial["popup-collection-padding"],
    outline: "none",
    overscrollBehavior: "contain",
    display: "flex",
    flexDirection: "column",
    maxHeight: "var(--available-height)",
    overflowY: "auto",
  },
  item: {
    borderRadius: borderRadii.xs,
    gap: spacing.m,
    outline: "none",
    paddingInline: spatial["popup-item-inline-padding"],
    alignItems: "center",
    backgroundColor: { default: "transparent", ":active": backgroundColors["bg-pressed"] },
    boxSizing: "border-box",
    cursor: "default",
    display: "grid",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.regular,
    gridTemplateColumns: `minmax(0, 1fr) ${spatial["icon-size-m"]}`,
    lineHeight: lineHeights.ui,
    userSelect: "none",
    minHeight: spatial["popup-row-min-height"],
    width: "100%",
  },
  itemSizeS: {},
  itemSizeM: { minHeight: spatial["popup-row-min-height-m"] },
  itemSizeL: { minHeight: spatial["popup-row-min-height-l"] },
  itemHighlighted: {
    backgroundColor: backgroundColors["bg-hover"],
  },
  itemSelected: { backgroundColor: backgroundColors["bg-selected"] },
  itemDisabled: {
    backgroundColor: { default: "transparent", ":active": "transparent" },
    color: textColors["text-disabled"],
  },
  itemText: { gridColumnStart: "1", minWidth: 0 },
  indicator: {
    alignItems: "center",
    display: "inline-flex",
    gridColumnStart: "2",
    justifyContent: "center",
    justifySelf: "end",
  },
  indicatorSelected: {},
  indicatorStarting: {},
  indicatorEnding: {},
  group: {},
  groupLabel: {
    paddingBlock: spatial["popup-collection-padding"],
    paddingInline: spatial["popup-item-inline-padding"],
    color: textColors["text-muted"],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.compact,
  },
  separator: {
    marginBlock: spatial["popup-collection-padding"],
    backgroundColor: borderColors["border-secondary"],
    height: 1,
  },
  separatorHorizontal: {},
  separatorVertical: {},
});
