import * as stylex from "@stylexjs/stylex";

import { layerIndexes } from "../../tokens/layers.stylex";
import { backgroundColors, borderColors, textColors } from "../../tokens/semantics.stylex";
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from "../../tokens/value.stylex";

export const selectStyles = stylex.create({
  label: {
    color: textColors["text-default"],
    cursor: "default",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.tight,
  },
  labelDisabled: { color: textColors["text-disabled"] },
  trigger: {
    borderColor: {
      default: borderColors.border,
      ":focus-visible": borderColors["border-focused"],
    },
    borderRadius: borderRadii.xs,
    borderStyle: "solid",
    borderWidth: 1,
    outlineWidth: 0,
    gap: spacing.l,
    alignItems: "center",
    appearance: "none",
    backgroundColor: {
      default: backgroundColors["bg-card"],
      ":hover": backgroundColors["bg-hover"],
      ":active": backgroundColors["bg-pressed"],
    },
    color: textColors["text-default"],
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    justifyContent: "space-between",
    lineHeight: lineHeights.none,
    userSelect: "none",
    whiteSpace: "nowrap",
    minWidth: 160,
  },
  sizeS: { height: 24, paddingInline: spacing.s },
  sizeM: { height: 28, paddingInline: spacing.m },
  sizeL: { height: 32, paddingInline: spacing.l },
  triggerFullWidth: { width: "100%" },
  triggerOpen: { backgroundColor: backgroundColors["bg-hover"] },
  triggerInvalid: {
    borderColor: {
      default: borderColors["border-danger"],
      ":focus-visible": borderColors["border-danger"],
    },
    outlineColor: borderColors["border-danger-subtle"],
    outlineOffset: 0,
    outlineStyle: "solid",
    outlineWidth: 2,
  },
  disabled: { color: textColors["text-disabled"], cursor: "not-allowed" },
  valuePlaceholder: { color: textColors["text-subtle"] },
  iconContainer: { alignItems: "center", display: "inline-flex", flexShrink: 0 },
  icon: { display: "block", height: 14, width: 14 },
  positioner: { outline: "none", userSelect: "none", zIndex: layerIndexes.popup },
  popup: {
    borderColor: borderColors.border,
    borderRadius: borderRadii.s,
    borderStyle: "solid",
    borderWidth: 1,
    outline: "none",
    backgroundColor: backgroundColors["bg-card"],
    color: textColors["text-default"],
    transformOrigin: "var(--transform-origin)",
    minWidth: "var(--anchor-width)",
  },
  popupTransition: { opacity: 0, transform: "scale(0.98)" },
  list: {
    paddingBlock: spacing.xs,
    maxHeight: "var(--available-height)",
    overflowY: "auto",
  },
  item: {
    borderRadius: borderRadii.xs,
    gap: spacing.m,
    outline: "none",
    paddingInline: spacing.m,
    alignItems: "center",
    boxSizing: "border-box",
    cursor: "default",
    display: "grid",
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    gridTemplateColumns: "minmax(0, 1fr) 16px",
    lineHeight: lineHeights.tight,
    userSelect: "none",
    minHeight: 28,
    width: "100%",
  },
  itemHighlighted: {
    backgroundColor: backgroundColors["bg-secondary"],
  },
  itemDisabled: { color: textColors["text-disabled"] },
  itemText: { gridColumnStart: "1", minWidth: 0 },
  indicator: {
    alignItems: "center",
    display: "inline-flex",
    gridColumnStart: "2",
    justifyContent: "center",
    justifySelf: "end",
  },
});
