import * as stylex from '@stylexjs/stylex'

import { layerIndexes } from '../../tokens/layers.stylex'
import {
  borderColors,
  elementColors,
  focusColors,
  ghostElementColors,
  spatial,
  surfaceColors,
  textColors,
} from '../../tokens/semantics.stylex'
import {
  borderRadii,
  dimensions,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  shadows,
  spacing,
} from '../../tokens/value.stylex'
import { comboboxStyleVars } from './comboboxVars.stylex'

export const comboboxStyles = stylex.create({
  inputGroup: {
    borderColor: {
      default: borderColors.default,
      ':focus-within': borderColors.focused,
    },
    borderRadius: borderRadii.xs,
    borderStyle: 'solid',
    borderWidth: 1,
    backgroundColor: surfaceColors.default,
    display: 'flex',
    outlineColor: focusColors.ring,
    outlineOffset: 0,
    outlineStyle: 'solid',
    outlineWidth: 0,
    minWidth: spatial['combobox-min-width'],
  },
  inputGroupInvalid: {
    borderColor: borderColors.danger,
    outlineColor: focusColors.ringDanger,
    outlineWidth: spatial['focus-ring-width'],
  },
  inputGroupDisabled: {
    borderColor: borderColors.subtle,
    backgroundColor: elementColors.disabled,
    outlineWidth: 0,
  },
  inputGroupOpen: {},
  inputGroupPressed: {},
  inputGroupReadOnly: {},
  inputGroupValid: {},
  inputGroupTouched: {},
  inputGroupDirty: {},
  inputGroupFilled: {},
  inputGroupFocused: {},
  inputGroupListEmpty: {},
  inputGroupPlaceholder: {},
  inputGroupSideTop: {},
  inputGroupSideBottom: {},
  inputGroupSideLeft: {},
  inputGroupSideRight: {},
  inputGroupSideInlineStart: {},
  inputGroupSideInlineEnd: {},
  inputGroupWidthFull: { width: '100%' },
  inputGroupBare: {
    borderColor: { default: 'transparent', ':focus-within': 'transparent' },
    borderWidth: 0,
    backgroundColor: 'transparent',
  },
  input: {
    borderWidth: 0,
    flex: '1',
    outline: 'none',
    paddingInline: spacing.s,
    appearance: 'none',
    backgroundColor: 'transparent',
    color: textColors.default,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.ui,
    height: `calc(${spatial['control-height-l']} - 2px)`,
    minWidth: 0,
    '::placeholder': { color: textColors.muted },
  },
  inputDisabled: { color: textColors.disabled, cursor: 'not-allowed' },
  inputOpen: {},
  inputPressed: {},
  inputReadOnly: {},
  inputValid: {},
  inputInvalid: {},
  inputTouched: {},
  inputDirty: {},
  inputFilled: {},
  inputFocused: {},
  inputListEmpty: {},
  inputSideTop: {},
  inputSideBottom: {},
  inputSideLeft: {},
  inputSideRight: {},
  inputSideInlineStart: {},
  inputSideInlineEnd: {},
  action: {
    padding: 0,
    borderWidth: 0,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: {
      default: 'transparent',
      ':hover': ghostElementColors.hover,
      ':active': ghostElementColors.pressed,
    },
    color: textColors.muted,
    cursor: 'pointer',
    display: 'inline-flex',
    justifyContent: 'center',
    height: `calc(${spatial['control-height-l']} - 2px)`,
    width: `calc(${spatial['control-height-l']} - 2px)`,
  },
  actionDisabled: {
    backgroundColor: { default: 'transparent', ':hover': 'transparent', ':active': 'transparent' },
    color: textColors.disabled,
    cursor: 'not-allowed',
  },
  inputTriggerOpen: {},
  inputTriggerPressed: {},
  inputTriggerValid: {},
  inputTriggerInvalid: {},
  inputTriggerTouched: {},
  inputTriggerDirty: {},
  inputTriggerFilled: {},
  inputTriggerFocused: {},
  inputTriggerListEmpty: {},
  inputTriggerPlaceholder: {},
  inputTriggerSideTop: {},
  inputTriggerSideBottom: {},
  inputTriggerSideLeft: {},
  inputTriggerSideRight: {},
  inputTriggerSideInlineStart: {},
  inputTriggerSideInlineEnd: {},
  icon: {
    display: 'block',
    transform: 'rotate(0deg)',
    transitionDuration: '250ms',
    transitionProperty: 'transform',
    height: spatial['icon-size-s'],
    width: spatial['icon-size-s'],
  },
  iconOpen: { transform: 'rotate(180deg)' },
  trigger: {
    [comboboxStyleVars.triggerTextColor]: textColors.default,
    paddingInline: spacing.xs,
    color: { default: textColors.default, ':disabled': textColors.disabled },
  },
  triggerOpen: {
    [comboboxStyleVars.triggerTextColor]: textColors.accent,
    backgroundColor: ghostElementColors.selected,
  },
  triggerPressed: {},
  triggerDisabled: {},
  triggerValid: {},
  triggerInvalid: {},
  triggerTouched: {},
  triggerDirty: {},
  triggerFilled: {},
  triggerFocused: {},
  triggerListEmpty: {},
  triggerPlaceholder: {},
  triggerSideTop: {},
  triggerSideBottom: {},
  triggerSideLeft: {},
  triggerSideRight: {},
  triggerSideInlineStart: {},
  triggerSideInlineEnd: {},
  triggerWidthContent: { width: 'fit-content' },
  triggerWidthS: { maxWidth: spatial['combobox-trigger-width-s'], width: 'fit-content' },
  triggerWidthM: { maxWidth: spatial['combobox-trigger-width-m'], width: 'fit-content' },
  triggerWidthFull: { width: '100%' },
  positioner: { outline: 'none', zIndex: layerIndexes.popup },
  positionerOpen: {},
  positionerClosed: {},
  positionerAnchorHidden: {},
  positionerEmpty: {},
  positionerSideTop: {},
  positionerSideBottom: {},
  positionerSideLeft: {},
  positionerSideRight: {},
  positionerSideInlineStart: {},
  positionerSideInlineEnd: {},
  positionerAlignStart: {},
  positionerAlignCenter: {},
  positionerAlignEnd: {},
  popup: {
    borderRadius: borderRadii.xs,
    outline: 'none',
    backgroundColor: surfaceColors.raised,
    boxShadow: shadows.medium,
    color: textColors.default,
    display: 'flex',
    flexDirection: 'column',
    transformOrigin: 'var(--transform-origin)',
    maxHeight: 'var(--available-height)',
    maxWidth: 'var(--available-width)',
    minWidth: 'var(--anchor-width)',
  },
  popupWidthAnchor: { width: 'var(--anchor-width)' },
  popupWidthContent: { width: 'max-content' },
  popupWidthS: { width: spatial['popup-width-s'] },
  popupWidthM: { width: spatial['popup-width-m'] },
  popupWidthL: { width: spatial['popup-width-l'] },
  popupTransition: { opacity: 0, transform: 'scale(0.98)' },
  popupOpen: {},
  popupClosed: {},
  popupAnchorHidden: {},
  popupEmpty: {},
  popupStarting: {},
  popupEnding: {},
  popupSideTop: {},
  popupSideBottom: {},
  popupSideLeft: {},
  popupSideRight: {},
  popupSideInlineStart: {},
  popupSideInlineEnd: {},
  popupAlignStart: {},
  popupAlignCenter: {},
  popupAlignEnd: {},
  popupSection: {
    padding: spatial['popup-collection-padding'],
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.ui,
  },
  popupHeader: {
    flexShrink: 0,
  },
  popupFooter: {
    flexShrink: 0,
  },
  viewport: {
    padding: spatial['popup-collection-padding'],
    overscrollBehavior: 'contain',
    minHeight: 0,
    overflowY: 'auto',
  },
  viewportHeightS: { maxHeight: spatial['viewport-height-s'] },
  viewportHeightM: { maxHeight: spatial['viewport-height-m'] },
  viewportHeightL: { maxHeight: spatial['viewport-height-l'] },
  viewportHeightFiveItems: { maxHeight: `calc(${dimensions[180]} + ${spacing.l})` },
  viewportHeightAvailable: { maxHeight: 'var(--available-height)' },
  list: {
    gap: spacing.xxs,
    outline: 'none',
    display: 'flex',
    flexDirection: 'column',
  },
  listEmpty: {},
  group: {
    display: 'flex',
    flexDirection: 'column',
  },
  groupLabel: {
    paddingBlock: spatial['popup-collection-padding'],
    paddingInline: spatial['popup-item-inline-padding'],
    color: textColors.muted,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.compact,
  },
  item: {
    borderRadius: borderRadii.xs,
    gap: spacing.m,
    outline: 'none',
    paddingInline: spatial['popup-item-inline-padding'],
    alignItems: 'center',
    boxSizing: 'border-box',
    cursor: 'default',
    display: 'grid',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.ui,
    userSelect: 'none',
    minHeight: spatial['collection-row-height-s'],
    width: 'auto',
  },
  itemWithIndicator: {
    gridTemplateColumns: `minmax(0, 1fr) ${spatial['icon-size-m']}`,
  },
  itemInteractive: {
    backgroundColor: {
      default: 'transparent',
      ':hover': ghostElementColors.hover,
      ':active': ghostElementColors.pressed,
    },
  },
  itemHighlighted: {
    backgroundColor: ghostElementColors.hover,
    outlineColor: { default: 'transparent', '@media (forced-colors: active)': 'Highlight' },
    outlineStyle: 'solid',
    outlineWidth: { default: 0, '@media (forced-colors: active)': 1 },
  },
  itemSelected: {
    backgroundColor: ghostElementColors.selected,
  },
  itemDisabled: {
    backgroundColor: { default: 'transparent', ':hover': 'transparent', ':active': 'transparent' },
    color: textColors.disabled,
    cursor: 'not-allowed',
  },
  indicator: {
    alignItems: 'center',
    display: 'inline-flex',
    gridColumnStart: '2',
    gridRowStart: '1',
    justifyContent: 'center',
    justifySelf: 'end',
  },
  indicatorSelected: {},
  indicatorStarting: {},
  indicatorEnding: {},
  itemText: {
    gap: spacing.xxs,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
  },
  itemLabel: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  itemDescription: {
    overflow: 'hidden',
    color: textColors.muted,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.compact,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  label: {
    color: textColors.default,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.ui,
  },
  labelDisabled: {},
  labelValid: {},
  labelInvalid: {},
  labelTouched: {},
  labelDirty: {},
  labelFilled: {},
  labelFocused: {},
  separator: {
    backgroundColor: borderColors.subtle,
    height: 1,
  },
  separatorHorizontal: {},
  separatorVertical: {},
  clearOpen: {},
  clearVisible: {},
  clearStarting: {},
  clearEnding: {},
  empty: {
    padding: { default: spacing.xs, ':empty': 0 },
    color: textColors.muted,
    display: 'block',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
  },
  status: {
    padding: { default: spacing.l, ':empty': 0 },
    color: textColors.muted,
    display: 'block',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
  },
})
