import * as stylex from '@stylexjs/stylex'

import { backgroundColors, borderColors, spatial, textColors } from '../../tokens/semantics.stylex'
import {
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from '../../tokens/value.stylex'

export const dataGridStyles = stylex.create({
  root: {
    backgroundColor: backgroundColors['bg-page'],
    color: textColors['text-default'],
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    width: '100%',
  },
  viewport: {
    overflow: 'auto',
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    minWidth: 0,
    width: '100%',
  },
  scrollSurface: {
    backgroundColor: backgroundColors['bg-page'],
    position: 'relative',
    minWidth: '100%',
  },
  scrollSurfacePaintBoundary: {
    contain: 'paint',
  },
  table: {
    borderCollapse: 'separate',
    borderSpacing: 0,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    lineHeight: lineHeights.compact,
    tableLayout: 'fixed',
    userSelect: 'none',
  },
  headerBackdropAnchor: {
    position: 'sticky',
    zIndex: 1,
    height: 0,
    top: 0,
  },
  headerBackdrop: {
    boxSizing: 'border-box',
    borderBottomColor: borderColors['border-table-header-cell'],
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    borderTopColor: borderColors['border-table-header-cell'],
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    height: spatial['control-height-l'],
    width: '100%',
  },
  compactHeaderBackdrop: {
    height: spatial['control-height-m'],
  },
  header: {
    position: 'sticky',
    zIndex: 4,
    top: 0,
  },
  headerCell: {
    backgroundColor: backgroundColors['bg-table-header'],
    boxSizing: 'border-box',
    color: textColors['text-secondary'],
    borderBottomColor: borderColors['border-table-header-cell'],
    borderTopColor: borderColors['border-table-header-cell'],
    borderBottomStyle: 'solid',
    overflow: 'hidden',
    borderBottomWidth: 1,
    borderTopWidth: 1,
    fontWeight: fontWeights.regular,
    borderRightColor: {
      default: borderColors['border-table-header-cell'],
      ':has([data-resizing])': borderColors['border-table-column-active'],
      ':has([data-slot="data-grid-resize-handle"]:focus-visible)':
        borderColors['border-table-column-active'],
      ':has([data-slot="data-grid-resize-handle"]:hover)':
        borderColors['border-table-column-active'],
    },
    outlineColor: {
      default: 'transparent',
      ':focus-visible': borderColors['border-table-column-active'],
    },
    outlineOffset: -2,
    borderRightStyle: 'solid',
    outlineStyle: 'solid',
    borderRightWidth: 1,
    outlineWidth: {
      default: 0,
      ':focus-visible': spatial['focus-ring-width'],
    },
    height: spatial['control-height-l'],
    position: 'sticky',
    textAlign: 'start',
    // paddingLeft: spacing.m,
    textOverflow: 'ellipsis',
    paddingBottom: 0,
    // paddingRight: spacing.m,
    whiteSpace: 'nowrap',
    zIndex: 2,
    paddingTop: 0,
    top: 0,
  },
  headerCellActive: {
    backgroundColor: backgroundColors['bg-table-header-cell-active'],
    color: textColors['text-default'],
    borderBottomColor: 'transparent',
    borderRightColor: {
      default: 'transparent',
      ':has([data-resizing])': borderColors['border-table-column-active'],
      ':has([data-slot="data-grid-resize-handle"]:focus-visible)':
        borderColors['border-table-column-active'],
      ':has([data-slot="data-grid-resize-handle"]:hover)':
        borderColors['border-table-column-active'],
    },
    borderTopColor: borderColors['border-table-column-active'],
    outlineColor: borderColors['border-table-column-active'],
    outlineOffset: {
      default: 0,
      ':focus-visible': -1,
    },
    outlineWidth: {
      default: 1,
      ':focus-visible': spatial['focus-ring-width'],
    },
    zIndex: 3,
  },
  headerCellLayout: {
    paddingLeft: 0,
    paddingRight: 0,
  },
  headerCellReorderable: {
    cursor: 'grab',
    touchAction: 'none',
  },
  headerCellDragging: {
    backgroundColor: 'transparent',
    cursor: 'grabbing',
    zIndex: 4,
    borderBottomColor: borderColors['border-table-column-active'],
  },
  headerDragContent: {
    alignItems: 'center',
    boxSizing: 'border-box',
    display: 'flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.regular,
    height: '100%',
    lineHeight: lineHeights.compact,
    overflow: 'hidden',
    paddingLeft: spacing.m,
    paddingRight: spacing.m,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    width: '100%',
  },
  headerDragSource: {
    color: 'inherit',
  },
  headerDragSourceDragging: {
    visibility: 'hidden',
  },
  compactCellInlinePadding: {
    paddingLeft: spacing.s,
    paddingRight: spacing.s,
  },
  columnDragOverlay: {
    boxSizing: 'border-box',
    pointerEvents: 'none',
    position: 'fixed',
  },
  columnDragOverlayContent: {
    backgroundColor: backgroundColors['bg-table-header-cell-active'],
    borderBottomColor: borderColors['border-table-column-active'],
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    color: textColors['text-default'],
  },
  row: {
    backgroundColor: backgroundColors['bg-page'],
  },
  rowSelected: {
    backgroundColor: 'transparent',
  },
  rowActive: {
    boxShadow: `inset 0 ${spatial['focus-ring-width']} 0 ${borderColors['border-table-cell-active']}`,
  },
  cell: {
    backgroundColor: 'transparent',
    boxSizing: 'border-box',
    fontFamily: fontFamilies.mono,
    borderBottomColor: borderColors['border-table-cell'],
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    overflow: 'hidden',
    borderRightColor: borderColors['border-table-cell'],
    outlineColor: {
      default: 'transparent',
      ':focus-visible': borderColors['border-table-cell-active'],
    },
    outlineOffset: -2,
    borderRightStyle: 'solid',
    borderRightWidth: 1,
    outlineStyle: 'solid',
    height: spatial['control-height-l'],
    outlineWidth: {
      default: 0,
      ':focus-visible': spatial['focus-ring-width'],
    },
    paddingBottom: 0,
    whiteSpace: 'nowrap',
    paddingLeft: spacing.m,
    paddingRight: spacing.m,
    paddingTop: 0,
  },
  cellColumnActive: {
    backgroundColor: backgroundColors['bg-table-column-cell-active'],
  },
  cellSelected: {
    backgroundColor: backgroundColors['bg-table-row-cell-selected'],
  },
  cellSelection: {
    backgroundColor: backgroundColors['bg-table-cell-active'],
  },
  cellActive: {
    backgroundColor: backgroundColors['bg-table-cell-active'],
    borderBottomColor: 'transparent',
    borderRightColor: 'transparent',
    outlineColor: borderColors['border-table-cell-active'],
    outlineOffset: {
      default: 0,
      ':focus-visible': -1,
    },
    outlineWidth: {
      default: 1,
      ':focus-visible': spatial['focus-ring-width'],
    },
    position: 'relative',
    zIndex: 1,
  },
  resizeHandle: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    cursor: 'col-resize',
    height: '100%',
    outlineColor: borderColors['border-table-column-active'],
    outlineOffset: -2,
    outlineStyle: 'solid',
    outlineWidth: {
      default: 0,
      ':focus-visible': spatial['focus-ring-width'],
    },
    padding: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    touchAction: 'none',
    width: spacing.s,
    zIndex: 3,
  },
  resizeHandleDragging: {
    visibility: 'hidden',
  },
  compactCell: {
    height: spatial['control-height-m'],
  },
  loadingIndicator: {
    gap: spacing.s,
    alignItems: 'center',
    display: 'inline-flex',
  },
  messageCell: {
    padding: spacing.xl,
    color: textColors['text-muted'],
    textAlign: 'center',
    height: spatial['viewport-height-s'],
  },
  virtualSpacerCell: {
    padding: 0,
    borderWidth: 0,
    height: 'inherit',
  },
  expandedCell: {
    padding: spacing.l,
    backgroundColor: backgroundColors['bg-subtle'],
    borderBottomColor: borderColors.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  footer: {
    alignItems: 'center',
    backgroundColor: backgroundColors['bg-page'],
    color: textColors['text-muted'],
    display: 'flex',
    flexShrink: 0,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    lineHeight: lineHeights.compact,
    borderTopColor: borderColors['border-secondary'],
    borderTopStyle: 'solid',
    borderTopWidth: 1,
    justifyContent: 'space-between',
    minHeight: spatial['control-height-l'],
    paddingLeft: spacing.l,
    paddingRight: spacing.l,
  },
})
