import * as stylex from '@stylexjs/stylex'

import {
  borderColors,
  dangerElementColors,
  focusColors,
  selectionColors,
  stagedChangeColors,
  surfaceColors,
  textColors,
} from '../../tokens/semantics.stylex'

export const dataGridColors = stylex.defineVars({
  background: surfaceColors.background,
  text: textColors.default,
  headerBackground: surfaceColors.default,
  headerBorder: borderColors.default,
  headerOutlineRest: 'transparent',
  headerText: textColors.secondary,
  emphasizedHeaderBackground: selectionColors.strongBackground,
  emphasizedHeaderBottomBorder: 'transparent',
  emphasizedHeaderSideBorder: 'transparent',
  emphasizedHeaderText: textColors.default,
  draggedHeaderBackground: 'transparent',
  draggedHeaderText: 'inherit',
  rowHoverBackground: surfaceColors.subtle,
  selectedRowBackground: 'transparent',
  stagedDeletionRowBackground: dangerElementColors.subtle,
  stagedDeletionRowBorder: borderColors.danger,
  stagedUpdateCellBackground: stagedChangeColors.background,
  stagedUpdateCellBorder: stagedChangeColors.border,
  currentRowBorder: selectionColors.border,
  cellBackground: 'transparent',
  cellBorder: borderColors.subtle,
  cellOutlineRest: 'transparent',
  emphasizedColumnBackground: selectionColors.background,
  emphasizedColumnBorder: selectionColors.border,
  selectedCellBackground: selectionColors.background,
  emphasizedCellBackground: selectionColors.background,
  currentCellInnerBorder: 'transparent',
  resizeHandleBackground: 'transparent',
  messageText: textColors.muted,
  expandedRowBackground: surfaceColors.subtle,
  expandedRowBorder: borderColors.default,
  footerBackground: surfaceColors.background,
  footerBorder: borderColors.subtle,
  footerText: textColors.muted,
  focusRing: focusColors.ring,
} as const)
