import * as stylex from '@stylexjs/stylex'

import { layerIndexes } from '../../tokens/layers.stylex'
import {
  accentElementColors,
  borderColors,
  focusColors,
  ghostElementColors,
  spatial,
  surfaceColors,
  textColors,
} from '../../tokens/semantics.stylex'
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  shadows,
  spacing,
} from '../../tokens/value.stylex'

export const calendarStyles = stylex.create({
  trigger: {
    borderColor: borderColors.default,
    borderRadius: borderRadii.xs,
    borderStyle: 'solid',
    borderWidth: 1,
    overflow: 'hidden',
    paddingInline: spacing.xs,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: {
      default: surfaceColors.default,
      ':hover': ghostElementColors.hover,
      ':active': ghostElementColors.pressed,
    },
    color: textColors.default,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    lineHeight: lineHeights.ui,
    textAlign: 'center',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    height: spatial['control-height-l'],
    minWidth: 0,
    width: '100%',
  },
  triggerGrouped: {
    borderRadius: 0,
    borderWidth: 0,
    flexBasis: '0%',
    flexGrow: 1,
    flexShrink: 1,
    outlineWidth: 0,
    height: '100%',
  },
  triggerOpen: { backgroundColor: ghostElementColors.selected },
  triggerClosed: {},
  triggerDisabled: {
    backgroundColor: surfaceColors.default,
    color: textColors.disabled,
    cursor: 'not-allowed',
  },
  positioner: { outline: 'none', zIndex: layerIndexes.popup },
  positionerOpen: {},
  positionerClosed: {},
  positionerAnchorHidden: {},
  positionerInstant: {},
  positionerSideTop: {},
  positionerSideBottom: {},
  positionerSideLeft: {},
  positionerSideRight: {},
  positionerSideInlineStart: {},
  positionerSideInlineEnd: {},
  positionerAlignStart: {},
  positionerAlignCenter: {},
  positionerAlignEnd: {},
  popup: {
    padding: spacing.s,
    borderColor: borderColors.default,
    borderRadius: borderRadii.xs,
    borderStyle: 'solid',
    borderWidth: 1,
    outline: 'none',
    backgroundColor: surfaceColors.raised,
    boxShadow: shadows.medium,
    color: textColors.default,
    display: 'flex',
    flexDirection: 'column',
    transformOrigin: 'var(--transform-origin)',
    maxHeight: 'var(--available-height)',
    maxWidth: 'var(--available-width)',
    width: spatial['multi-select-width-s'],
  },
  popupOpen: {},
  popupClosed: {},
  popupStarting: { opacity: 0, transform: 'scale(0.98)' },
  popupEnding: { opacity: 0, transform: 'scale(0.98)' },
  popupInstant: {},
  popupSideTop: {},
  popupSideBottom: {},
  popupSideLeft: {},
  popupSideRight: {},
  popupSideInlineStart: {},
  popupSideInlineEnd: {},
  popupAlignStart: {},
  popupAlignCenter: {},
  popupAlignEnd: {},
  calendarRoot: { fontFamily: fontFamilies.sans, width: '100%' },
  months: { display: 'flex', width: '100%' },
  month: {
    gap: spacing.xs,
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    width: '100%',
  },
  monthCaption: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
    height: spatial['control-height-s'],
  },
  dropdowns: {
    gap: spacing.xs,
    alignItems: 'center',
    display: 'flex',
    height: spatial['control-height-s'],
  },
  dropdownRoot: {
    borderRadius: borderRadii.xs,
    outlineColor: focusColors.ring,
    outlineOffset: -1,
    outlineStyle: 'solid',
    outlineWidth: { default: 0, ':focus-within': spatial['focus-ring-width'] },
    position: 'relative',
    height: spatial['control-height-s'],
  },
  dropdown: {
    inset: 0,
    cursor: 'pointer',
    opacity: 0,
    position: 'absolute',
    height: spatial['control-height-s'],
    width: '100%',
  },
  captionLabel: {
    gap: spacing.xxs,
    paddingInline: spacing.xs,
    alignItems: 'center',
    display: 'inline-flex',
    fontSize: fontSizes[2],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.ui,
    height: spatial['control-height-s'],
  },
  nav: {
    insetInline: 0,
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    pointerEvents: 'none',
    position: 'absolute',
    height: spatial['control-height-s'],
    top: 0,
  },
  navButton: {
    padding: 0,
    borderRadius: borderRadii.xs,
    borderWidth: 0,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: {
      default: 'transparent',
      ':hover': ghostElementColors.hover,
      ':active': ghostElementColors.pressed,
    },
    color: { default: textColors.muted, ':disabled': textColors.disabled },
    cursor: { default: 'pointer', ':disabled': 'not-allowed' },
    display: 'inline-flex',
    justifyContent: 'center',
    outlineColor: focusColors.ring,
    outlineOffset: -1,
    outlineStyle: 'solid',
    outlineWidth: { default: 0, ':focus-visible': spatial['focus-ring-width'] },
    pointerEvents: 'auto',
    height: spatial['control-height-s'],
    width: spatial['control-height-s'],
  },
  navButtonPrevious: { insetInlineStart: 0, position: 'absolute', top: 0 },
  navButtonNext: { insetInlineEnd: 0, position: 'absolute', top: 0 },
  chevron: { display: 'block', height: spatial['icon-size-s'], width: spatial['icon-size-s'] },
  monthGrid: {
    borderCollapse: 'separate',
    tableLayout: 'fixed',
    width: '100%',
  },
  weekday: {
    color: textColors.muted,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.compact,
    textAlign: 'center',
    height: spatial['control-height-m'],
  },
  day: {
    padding: 0,
    textAlign: 'center',
    height: spatial['control-height-m'],
    width: spatial['control-height-m'],
  },
  dayButton: {
    padding: 0,
    borderRadius: borderRadii.xs,
    borderWidth: 0,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: {
      default: 'transparent',
      ':hover': ghostElementColors.hover,
      ':active': ghostElementColors.pressed,
    },
    color: textColors.default,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontVariantNumeric: 'tabular-nums',
    justifyContent: 'center',
    lineHeight: lineHeights.ui,
    outlineColor: focusColors.ring,
    outlineOffset: -1,
    outlineStyle: 'solid',
    outlineWidth: { default: 0, ':focus-visible': spatial['focus-ring-width'] },
    height: spatial['control-height-m'],
    width: spatial['control-height-m'],
  },
  daySelected: {
    backgroundColor: {
      default: accentElementColors.default,
      ':hover': accentElementColors.hover,
      ':active': accentElementColors.pressed,
    },
    color: textColors.onAccent,
  },
  dayOutside: { color: textColors.disabled },
  dayDisabled: { color: textColors.disabled, cursor: 'not-allowed' },
  dayHidden: { visibility: 'hidden' },
  controls: {
    gap: spacing.s,
    display: 'flex',
    flexDirection: 'column',
    paddingTop: spacing.m,
  },
  timeRow: { gap: spacing.s, alignItems: 'flex-end', display: 'flex' },
  controlLabel: {
    color: textColors.muted,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    lineHeight: lineHeights.compact,
  },
  field: {
    gap: spacing.xs,
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  input: {
    textAlign: 'center',
  },
  setNowAction: { flexShrink: 0 },
  applyAction: { width: '100%' },
})
