export const boxPropNames = [
  'as',
  'display',
  'flexDirection',
  'gap',
  'padding',
  'backgroundColor',
  'borderColor',
  'borderRadius',
  'borderStyle',
  'borderWidth',
  'overflow',
  'scrollbar',
  'scrollbarGutter',
] as const
