/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bef9d32c5743cca56b9e83729c5058fa)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	PRODUCT: Fetcher /* inspektor-product */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/siteWorker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
