import * as stylex from '@stylexjs/stylex'

import {
  accentElementColors,
  focusColors,
  ghostElementColors,
  spatial,
  textColors,
} from '../../tokens/semantics.stylex'
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from '../../tokens/value.stylex'

export const calendarStyles = stylex.create({
  standalone: { width: spatial['multi-select-width-s'] },
  calendarRoot: { fontFamily: fontFamilies.sans, width: '100%' },
  calendarSurface: {
    gap: spacing.xs,
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  visuallyHidden: {
    overflow: 'hidden',
    clip: 'rect(0 0 0 0)',
    clipPath: 'inset(50%)',
    position: 'absolute',
    whiteSpace: 'nowrap',
    height: 1,
    width: 1,
  },
  calendarHeader: {
    gap: spacing.xxs,
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    height: spatial['control-height-s'],
  },
  headerLabels: {
    gap: spacing.xxs,
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
  },
  headerButton: {
    borderRadius: borderRadii.xs,
    borderWidth: 0,
    paddingInline: spacing.xs,
    appearance: 'none',
    backgroundColor: {
      default: 'transparent',
      ':hover': ghostElementColors.hover,
      ':active': ghostElementColors.pressed,
    },
    color: { default: textColors.default, ':disabled': textColors.disabled },
    cursor: { default: 'pointer', ':disabled': 'not-allowed' },
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.ui,
    outlineColor: focusColors.ring,
    outlineOffset: -1,
    outlineStyle: 'solid',
    outlineWidth: { default: 0, ':focus-visible': spatial['focus-ring-width'] },
    whiteSpace: 'nowrap',
    height: spatial['control-height-s'],
  },
  headerButtonSelected: {
    backgroundColor: accentElementColors.default,
    color: textColors.onAccent,
  },
  calendarView: {
    alignItems: 'center',
    display: 'flex',
    minHeight: `calc(${spatial['control-height-m']} * 7)`,
    width: '100%',
  },
  calendarViewSelector: { minHeight: 0 },
  months: { display: 'flex', width: '100%' },
  month: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  navButton: {
    padding: 0,
    borderRadius: borderRadii.xs,
    borderWidth: 0,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: {
      default: 'transparent',
      ':hover': ghostElementColors.hover,
      ':active': ghostElementColors.pressed,
    },
    color: { default: textColors.muted, ':disabled': textColors.disabled },
    cursor: { default: 'pointer', ':disabled': 'not-allowed' },
    display: 'inline-flex',
    justifyContent: 'center',
    outlineColor: focusColors.ring,
    outlineOffset: -1,
    outlineStyle: 'solid',
    outlineWidth: { default: 0, ':focus-visible': spatial['focus-ring-width'] },
    height: spatial['control-height-s'],
    width: spatial['control-height-s'],
  },
  chevron: { display: 'block', height: spatial['icon-size-s'], width: spatial['icon-size-s'] },
  selectorGrid: {
    gap: spacing.xs,
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  selectorRow: {
    gap: spacing.xxs,
    display: 'grid',
    width: '100%',
  },
  selectorRowMonths: { gridTemplateColumns: 'repeat(3, minmax(0, 1fr))' },
  selectorRowYears: { gridTemplateColumns: 'repeat(5, minmax(0, 1fr))' },
  selectorButton: {
    borderRadius: borderRadii.xs,
    borderWidth: 0,
    paddingInline: spacing.xxs,
    appearance: 'none',
    backgroundColor: {
      default: 'transparent',
      ':hover': ghostElementColors.hover,
      ':active': ghostElementColors.pressed,
    },
    color: { default: textColors.default, ':disabled': textColors.disabled },
    cursor: { default: 'pointer', ':disabled': 'not-allowed' },
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontVariantNumeric: 'tabular-nums',
    lineHeight: lineHeights.ui,
    outlineColor: focusColors.ring,
    outlineOffset: -1,
    outlineStyle: 'solid',
    outlineWidth: { default: 0, ':focus-visible': spatial['focus-ring-width'] },
    textAlign: 'center',
    height: spatial['control-height-m'],
    width: '100%',
  },
  selectorButtonSelected: {
    backgroundColor: {
      default: accentElementColors.default,
      ':hover': accentElementColors.hover,
      ':active': accentElementColors.pressed,
    },
    color: textColors.onAccent,
  },
  monthGrid: {
    borderCollapse: 'separate',
    tableLayout: 'fixed',
    width: '100%',
  },
  weekday: {
    color: textColors.muted,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.compact,
    textAlign: 'center',
    height: spatial['control-height-m'],
  },
  day: {
    padding: 0,
    textAlign: 'center',
    height: spatial['control-height-m'],
    width: spatial['control-height-m'],
  },
  dayButton: {
    padding: 0,
    borderRadius: borderRadii.xs,
    borderWidth: 0,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: {
      default: 'transparent',
      ':hover': ghostElementColors.hover,
      ':active': ghostElementColors.pressed,
    },
    color: textColors.default,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontVariantNumeric: 'tabular-nums',
    justifyContent: 'center',
    lineHeight: lineHeights.ui,
    outlineColor: focusColors.ring,
    outlineOffset: -1,
    outlineStyle: 'solid',
    outlineWidth: { default: 0, ':focus-visible': spatial['focus-ring-width'] },
    height: spatial['control-height-m'],
    width: spatial['control-height-m'],
  },
  daySelected: {
    backgroundColor: {
      default: accentElementColors.default,
      ':hover': accentElementColors.hover,
      ':active': accentElementColors.pressed,
    },
    color: textColors.onAccent,
  },
  dayOutside: { color: textColors.disabled },
  dayDisabled: { color: textColors.disabled, cursor: 'not-allowed' },
  dayHidden: { visibility: 'hidden' },
})
