import * as stylex from '@stylexjs/stylex'

import {
  backgroundColors,
  borderColors,
  spatial,
  textColors,
} from '../../tokens/semantics.stylex'
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from '../../tokens/value.stylex'
import { tabViewVars } from './tabViewVars.stylex'

export const tabViewStyles = stylex.create({
  root: {
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    width: '100%',
  },
  list: {
    gap: spacing.s,
    overflow: 'clip',
    alignItems: 'center',
    display: 'flex',
    flexShrink: 1,
    minWidth: 0,
    width: 'max-content',
  },
  item: {
    [tabViewVars.background]: {
      default: backgroundColors['bg-tab'],
      ':focus-within': backgroundColors['bg-tab-hover'],
      ':hover': backgroundColors['bg-tab-hover'],
    },
    [tabViewVars.closeBackground]: {
      default: 'transparent',
      ':focus-within': tabViewVars.background,
      ':hover': tabViewVars.background,
    },
    [tabViewVars.closeOpacity]: {
      default: 0,
      ':focus-within': 1,
      ':hover': 1,
    },
    [tabViewVars.closePointerEvents]: {
      default: 'none',
      ':focus-within': 'auto',
      ':hover': 'auto',
    },
    [tabViewVars.fadeRight]: {
      default: '0',
      ':focus-within': '100%',
      ':hover': '100%',
    },
    borderRadius: borderRadii.s,
    overflow: 'hidden',
    alignItems: 'center',
    backgroundColor: tabViewVars.background,
    containerType: 'inline-size',
    display: 'flex',
    flexBasis: spatial['tab-view-width'],
    flexGrow: 0,
    flexShrink: 1,
    position: 'relative',
    height: spatial['control-height-m'],
    maxWidth: spatial['tab-view-width'],
    minWidth: spatial['control-height-m'],
    width: spatial['tab-view-width'],
  },
  itemActive: {
    [tabViewVars.background]: {
      default: backgroundColors['bg-tab-selected'],
      ':focus-within': backgroundColors['bg-tab-selected'],
      ':hover': backgroundColors['bg-tab-selected'],
    },
    [tabViewVars.closeBackground]: tabViewVars.background,
    [tabViewVars.closeOpacity]: 1,
    [tabViewVars.closePointerEvents]: 'auto',
    [tabViewVars.fadeRight]: '100%',
  },
  itemDisabled: {
    [tabViewVars.background]: {
      default: 'transparent',
      ':focus-within': 'transparent',
      ':hover': 'transparent',
    },
    [tabViewVars.closeOpacity]: 0,
    [tabViewVars.closePointerEvents]: 'none',
    opacity: 0.6,
  },
  tab: {
    borderStyle: 'none',
    gap: spacing.s,
    paddingInline: spacing.s,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: 'transparent',
    color: {
      default: textColors['text-muted'],
      ':hover': textColors['text-secondary'],
    },
    cursor: 'pointer',
    display: 'flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.none,
    outlineColor: borderColors['border-focused'],
    outlineOffset: -2,
    outlineStyle: {
      default: 'none',
      ':focus-visible': 'solid',
    },
    outlineWidth: spatial['focus-ring-width'],
    textAlign: 'start',
    userSelect: 'none',
    height: '100%',
    minWidth: 0,
    width: '100%',
  },
  tabActive: {
    color: textColors['text-default'],
  },
  tabDisabled: {
    color: textColors['text-disabled'],
    cursor: 'not-allowed',
  },
  prefix: {
    alignItems: 'center',
    display: 'flex',
    flexShrink: 0,
    justifyContent: 'center',
    height: spatial['icon-size-m'],
    width: spatial['icon-size-m'],
  },
  title: {
    overflow: 'hidden',
    display: 'block',
    flexGrow: 1,
    flexShrink: 1,
    textOverflow: 'clip',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  closeContainer: {
    alignItems: 'center',
    backgroundColor: tabViewVars.closeBackground,
    display: 'flex',
    justifyContent: 'center',
    pointerEvents: tabViewVars.closePointerEvents,
    position: 'absolute',
    zIndex: 1,
    height: 20,
    right: spacing.xs,
    top: spacing.xs,
    width: 20,
  },
  closeContainerOverflowing: {
    '::before': {
      backgroundImage: `linear-gradient(to right, transparent, ${tabViewVars.background})`,
      content: '',
      pointerEvents: 'none',
      position: 'absolute',
      zIndex: 0,
      height: 28,
      right: tabViewVars.fadeRight,
      top: -4,
      width: 16,
    },
  },
  closeButton: {
    padding: 0,
    borderRadius: borderRadii.s,
    borderStyle: 'none',
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: {
      default: 'transparent',
      ':hover': backgroundColors['bg-hover'],
    },
    color: textColors['text-muted'],
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    opacity: tabViewVars.closeOpacity,
    outlineColor: borderColors['border-focused'],
    outlineOffset: -2,
    outlineStyle: {
      default: 'none',
      ':focus-visible': 'solid',
    },
    outlineWidth: spatial['focus-ring-width'],
    zIndex: 1,
    height: 20,
    width: 20,
  },
  closeIcon: {
    display: 'block',
    position: 'relative',
    zIndex: 1,
    height: spatial['icon-size-m'],
    width: spatial['icon-size-m'],
  },
  panel: {
    overflow: 'hidden',
    flexGrow: 1,
    outlineColor: borderColors['border-focused'],
    outlineOffset: -2,
    outlineStyle: {
      default: 'none',
      ':focus-visible': 'solid',
    },
    outlineWidth: spatial['focus-ring-width'],
    minHeight: 0,
    minWidth: 0,
    width: '100%',
  },
})
