import * as stylex from '@stylexjs/stylex'

import {
  backgroundColors,
  borderColors,
  spatial,
  textColors,
} from '../../tokens/semantics.stylex'
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  spacing,
} from '../../tokens/value.stylex'
import { tabViewVars } from './tabViewVars.stylex'

export const tabViewStyles = stylex.create({
  root: {
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    width: '100%',
  },
  rootHorizontal: {},
  rootVertical: {},
  rootActivationLeft: {},
  rootActivationRight: {},
  rootActivationUp: {},
  rootActivationDown: {},
  rootActivationNone: {},
  list: {
    gap: spacing.xs,
    alignItems: 'center',
    display: 'flex',
    flexShrink: 1,
    minWidth: 0,
    overflowX: 'auto',
    overflowY: 'clip',
    width: 'max-content',
  },
  listHorizontal: {},
  listVertical: {},
  listActivationLeft: {},
  listActivationRight: {},
  listActivationUp: {},
  listActivationDown: {},
  listActivationNone: {},
  item: {
    [tabViewVars.background]: {
      default: backgroundColors['bg-tab'],
      ':focus-within': backgroundColors['bg-tab-hover'],
      ':hover': backgroundColors['bg-tab-hover'],
    },
    [tabViewVars.closeBackground]: {
      default: 'transparent',
      ':focus-within': tabViewVars.background,
      ':hover': tabViewVars.background,
    },
    [tabViewVars.closeOpacity]: {
      default: 0,
      ':focus-within': 1,
      ':hover': 1,
    },
    [tabViewVars.closePointerEvents]: {
      default: 'none',
      ':focus-within': 'auto',
      ':hover': 'auto',
    },
    borderRadius: borderRadii.xs,
    overflow: 'hidden',
    alignItems: 'center',
    backgroundColor: tabViewVars.background,
    display: 'flex',
    flexBasis: 'auto',
    flexGrow: 0,
    flexShrink: 1,
    outlineColor: borderColors['outline'],
    outlineOffset: -2,
    outlineStyle: {
      default: 'none',
      ':has([data-slot="tab-view-tab"]:focus-visible)': 'solid',
    },
    outlineWidth: spatial['focus-ring-width'],
    position: 'relative',
    height: spatial['tab-height'],
    maxWidth: spatial['tab-view-width'],
    minWidth: spatial['tab-view-min-width'],
    width: 'fit-content',
  },
  itemActive: {
    [tabViewVars.background]: backgroundColors['bg-tab-selected'],
    [tabViewVars.closeBackground]: tabViewVars.background,
    [tabViewVars.closeOpacity]: 1,
    [tabViewVars.closePointerEvents]: 'auto',
  },
  itemDragging: {
    [tabViewVars.background]: backgroundColors['bg-tab-hover'],
    [tabViewVars.closeBackground]: tabViewVars.background,
    [tabViewVars.closeOpacity]: 1,
    [tabViewVars.closePointerEvents]: 'auto',
  },
  itemDisabled: {
    [tabViewVars.background]: 'transparent',
    [tabViewVars.closeOpacity]: 0,
    [tabViewVars.closePointerEvents]: 'none',
    opacity: 0.6,
  },
  tab: {
    borderRadius: borderRadii.xs,
    borderStyle: 'none',
    gap: spacing.xs,
    paddingInline: spacing.xs,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: 'transparent',
    color: {
      default: textColors['text-muted'],
      ':hover': textColors['text-secondary'],
    },
    cursor: 'pointer',
    display: 'flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.regular,
    justifyContent: 'flex-start',
    lineHeight: lineHeights.ui,
    outlineStyle: 'none',
    textAlign: 'start',
    userSelect: 'none',
    height: '100%',
    minWidth: 0,
    width: '100%',
  },
  tabClosable: {
    paddingRight: `calc(${spatial['control-height-s']} + ${spacing.xxs})`,
  },
  tabActive: {
    color: textColors['text-default'],
  },
  tabDisabled: {
    color: textColors['text-disabled'],
    cursor: 'not-allowed',
  },
  tabHorizontal: {},
  tabVertical: {},
  tabActivationLeft: {},
  tabActivationRight: {},
  tabActivationUp: {},
  tabActivationDown: {},
  tabActivationNone: {},
  prefix: {
    alignItems: 'center',
    display: 'flex',
    flexShrink: 0,
    justifyContent: 'center',
    height: spatial['icon-size-m'],
    width: spatial['icon-size-m'],
  },
  title: {
    overflow: 'hidden',
    display: 'block',
    flexGrow: 1,
    flexShrink: 1,
    textOverflow: 'clip',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  closeContainer: {
    alignItems: 'center',
    backgroundColor: tabViewVars.closeBackground,
    display: 'flex',
    justifyContent: 'flex-start',
    pointerEvents: tabViewVars.closePointerEvents,
    position: 'absolute',
    transform: 'translateY(-50%)',
    zIndex: 1,
    height: spatial['button-height-xs'],
    right: 0,
    top: '50%',
    width: spatial['control-height-s'],
  },
  closeContainerOverflowing: {
    '::before': {
      backgroundImage: `linear-gradient(to right, transparent, ${tabViewVars.background})`,
      content: '',
      pointerEvents: 'none',
      position: 'absolute',
      zIndex: 0,
      height: '100%',
      right: '100%',
      top: 0,
      width: spacing.xl,
    },
  },
  closeAction: {
    opacity: tabViewVars.closeOpacity,
    outlineOffset: {
      default: 0,
      ':focus-visible': 0,
    },
    zIndex: 1,
  },
  closeIcon: {
    color: textColors['text-muted'],
    display: 'block',
    position: 'relative',
    zIndex: 1,
    height: spatial['icon-size-s'],
    width: spatial['icon-size-s'],
  },
  panel: {
    overflow: 'hidden',
    flexGrow: 1,
    outlineColor: borderColors['outline'],
    outlineOffset: -2,
    outlineStyle: {
      default: 'none',
      ':focus-visible': 'solid',
    },
    outlineWidth: spatial['focus-ring-width'],
    minHeight: 0,
    minWidth: 0,
    width: '100%',
  },
  panelHidden: {},
  panelIndexed: {},
  panelHorizontal: {},
  panelVertical: {},
  panelActivationLeft: {},
  panelActivationRight: {},
  panelActivationUp: {},
  panelActivationDown: {},
  panelActivationNone: {},
  panelStarting: {},
  panelEnding: {},
})
