import * as stylex from '@stylexjs/stylex'

import { layerIndexes } from '../../tokens/layers.stylex'
import { backgroundColors, borderColors, spatial, textColors } from '../../tokens/semantics.stylex'
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  shadows,
  spacing,
} from '../../tokens/value.stylex'

const reducedMotion = '@media (prefers-reduced-motion: reduce)'
const compactViewport = '@media (max-width: 639px)'

export const toasterStyles = stylex.create({
  viewport: {
    margin: 0,
    padding: 0,
    listStyle: 'none',
    outline: 'none',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: fontFamilies.sans,
    position: 'fixed',
    zIndex: layerIndexes.toast,
    bottom: { default: spacing.xl, [compactViewport]: spacing.m },
    left: { default: 'auto', [compactViewport]: spacing.m },
    right: { default: spacing.xl, [compactViewport]: spacing.m },
    width: { default: spatial['popup-width-m'], [compactViewport]: 'auto' },
  },
  toast: {
    borderColor: borderColors.border,
    borderRadius: borderRadii.l,
    borderStyle: 'solid',
    borderWidth: 1,
    alignItems: 'stretch',
    backgroundColor: backgroundColors['bg-popover'],
    boxShadow: shadows.medium,
    color: textColors['text-default'],
    cursor: 'default',
    opacity: 1,
    overflowWrap: 'anywhere',
    position: 'absolute',
    transform:
      'translateX(var(--toast-swipe-movement-x)) translateY(calc(var(--toast-swipe-movement-y) - var(--toast-index) * 8px)) scale(calc(1 - var(--toast-index) * 0.04))',
    transformOrigin: 'bottom right',
    transitionDuration: { default: '240ms', [reducedMotion]: '0ms' },
    transitionProperty: 'transform, opacity, height',
    transitionTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    userSelect: 'none',
    bottom: 0,
    height: 'var(--toast-frontmost-height, var(--toast-height))',
    right: 0,
    width: '100%',
  },
  toastExpanded: {
    height: 'var(--toast-height)',
    transform:
      'translateX(var(--toast-swipe-movement-x)) translateY(calc(var(--toast-offset-y) * -1 + var(--toast-swipe-movement-y)))',
  },
  toastLimited: { opacity: 0 },
  toastStarting: { opacity: 0, transform: 'translateY(100%)' },
  toastEnding: { opacity: 0, transform: 'translateY(100%)' },
  toastEndingLeft: { transform: 'translateX(calc(var(--toast-swipe-movement-x) - 125%))' },
  toastEndingRight: { transform: 'translateX(calc(var(--toast-swipe-movement-x) + 125%))' },
  toastEndingUp: { transform: 'translateY(calc(var(--toast-swipe-movement-y) - 125%))' },
  toastEndingDown: { transform: 'translateY(calc(var(--toast-swipe-movement-y) + 125%))' },
  content: {
    gap: spacing.l,
    overflow: 'hidden',
    paddingBlock: spacing.l,
    paddingInline: spacing.xl,
    alignItems: 'center',
    display: 'flex',
    opacity: 1,
    transitionDuration: { default: '160ms', [reducedMotion]: '0ms' },
    transitionProperty: 'opacity',
    transitionTimingFunction: 'ease-out',
    height: '100%',
    minHeight: 56,
  },
  contentBehind: { opacity: 0 },
  contentExpanded: { opacity: 1 },
  icon: {
    alignItems: 'center',
    display: 'flex',
    flexShrink: 0,
    justifyContent: 'center',
    height: spatial['icon-size-m'],
    width: spatial['icon-size-m'],
  },
  iconMessage: { color: textColors['text-muted'] },
  iconSuccess: { color: borderColors['border-success'] },
  iconWarning: { color: textColors['fg-notification-warning'] },
  iconError: { color: textColors['fg-notification-error'] },
  iconLoading: { color: textColors['fg-notification-loading'] },
  text: {
    gap: spacing.xxs,
    display: 'flex',
    flexDirection: 'column',
    flexGrow: 1,
    minWidth: 0,
  },
  title: {
    margin: 0,
    color: textColors['text-default'],
    fontSize: fontSizes[2],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.tight,
  },
  description: {
    margin: 0,
    color: textColors['text-muted'],
    fontSize: fontSizes[1],
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.normal,
  },
  action: {
    borderColor: borderColors['border-secondary'],
    borderRadius: borderRadii.m,
    borderStyle: 'solid',
    borderWidth: 1,
    paddingInline: spacing.m,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: {
      default: backgroundColors['bg-subtle'],
      ':hover': backgroundColors['bg-hover'],
      ':active': backgroundColors['bg-pressed'],
    },
    color: textColors['text-default'],
    cursor: 'pointer',
    display: 'flex',
    flexShrink: 0,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.medium,
    outlineColor: borderColors['border-focused'],
    outlineOffset: 1,
    outlineStyle: 'solid',
    outlineWidth: { default: 0, ':focus-visible': spatial['focus-ring-width'] },
    height: spatial['control-height-s'],
  },
  close: {
    padding: 0,
    borderColor: 'transparent',
    borderRadius: borderRadii.m,
    borderStyle: 'solid',
    borderWidth: 1,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: {
      default: 'transparent',
      ':hover': backgroundColors['bg-hover'],
      ':active': backgroundColors['bg-pressed'],
    },
    color: textColors['text-muted'],
    cursor: 'pointer',
    display: 'flex',
    flexShrink: 0,
    justifyContent: 'center',
    outlineColor: borderColors['border-focused'],
    outlineOffset: 1,
    outlineStyle: 'solid',
    outlineWidth: { default: 0, ':focus-visible': spatial['focus-ring-width'] },
    height: spatial['control-height-s'],
    width: spatial['control-height-s'],
  },
  closeIcon: { display: 'block', height: spatial['icon-size-s'], width: spatial['icon-size-s'] },
})
