import * as stylex from '@stylexjs/stylex'

import { breakpointQueries } from '../../tokens/breakpoints.stylex'
import { layerIndexes } from '../../tokens/layers.stylex'
import { backgroundColors, borderColors, spatial, textColors } from '../../tokens/semantics.stylex'
import {
  borderRadii,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  shadows,
  spacing,
} from '../../tokens/value.stylex'

const reducedMotion = '@media (prefers-reduced-motion: reduce)'
const compactViewport = breakpointQueries.belowSm

const pulseEven = stylex.keyframes({
  '0%, 100%': { scale: 1 },
  '50%': { scale: 1.04 },
})

const pulseOdd = stylex.keyframes({
  '0%, 100%': { scale: 1 },
  '49.999%, 50%': { scale: 1.04 },
})

export const toasterStyles = stylex.create({
  viewport: {
    margin: 0,
    padding: 0,
    listStyle: 'none',
    outline: 'none',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: fontFamilies.sans,
    position: 'fixed',
    zIndex: layerIndexes.toast,
    bottom: { default: spacing.xl, [compactViewport]: spacing.m },
    left: { default: 'auto', [compactViewport]: spacing.m },
    right: { default: spacing.xl, [compactViewport]: spacing.m },
    width: { default: spatial['popup-width-l'], [compactViewport]: 'auto' },
  },
  viewportExpanded: {},
  toast: {
    borderColor: borderColors.border,
    borderRadius: borderRadii.xs,
    borderStyle: 'solid',
    borderWidth: 1,
    alignItems: 'stretch',
    backgroundColor: backgroundColors['bg-popover'],
    boxShadow: shadows.medium,
    color: textColors['text-default'],
    cursor: 'default',
    opacity: 1,
    overflowWrap: 'anywhere',
    position: 'absolute',
    transform:
      `translateX(var(--toast-swipe-movement-x)) translateY(calc(var(--toast-swipe-movement-y) - var(--toast-index) * ${spacing.m})) scale(calc(1 - var(--toast-index) * 0.04))`,
    transformOrigin: 'bottom right',
    transitionDuration: { default: '240ms', [reducedMotion]: '0ms' },
    transitionProperty: 'transform, opacity, height',
    transitionTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    userSelect: 'none',
    bottom: 0,
    height: 'var(--toast-frontmost-height, var(--toast-height))',
    right: 0,
    width: '100%',
    '::after': {
      content: '',
      position: 'absolute',
      height: spacing.m,
      left: 0,
      top: '100%',
      width: '100%',
    },
  },
  toastFrontmost: { zIndex: 3 },
  toastMiddle: { zIndex: 2 },
  toastBack: { zIndex: 1 },
  pulseEven: {
    animationDuration: '280ms',
    animationName: { default: pulseEven, [reducedMotion]: 'none' },
    animationTimingFunction: 'ease',
  },
  pulseOdd: {
    animationDuration: '280ms',
    animationName: { default: pulseOdd, [reducedMotion]: 'none' },
    animationTimingFunction: 'ease',
  },
  toastExpanded: {
    height: 'var(--toast-height)',
    transform:
      `translateX(var(--toast-swipe-movement-x)) translateY(calc(var(--toast-offset-y) * -1 - var(--toast-index) * ${spacing.m} + var(--toast-swipe-movement-y)))`,
  },
  toastLimited: { opacity: 0, zIndex: 0 },
  toastStarting: { opacity: 0, transform: 'translateY(100%)' },
  toastEnding: { opacity: 0, transform: 'translateY(100%)' },
  toastEndingLeft: { transform: 'translateX(calc(var(--toast-swipe-movement-x) - 125%))' },
  toastEndingRight: { transform: 'translateX(calc(var(--toast-swipe-movement-x) + 125%))' },
  toastEndingUp: { transform: 'translateY(calc(var(--toast-swipe-movement-y) - 125%))' },
  toastEndingDown: { transform: 'translateY(calc(var(--toast-swipe-movement-y) + 125%))' },
  toastSwiping: {},
  toastSwipeLeft: {},
  toastSwipeRight: {},
  toastSwipeUp: {},
  toastSwipeDown: {},
  content: {
    overflow: 'hidden',
    paddingBlock: spacing.m,
    paddingInline: spacing.m,
    alignItems: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    opacity: 1,
    transitionDuration: { default: '160ms', [reducedMotion]: '0ms' },
    transitionProperty: 'opacity',
    transitionTimingFunction: 'ease-out',
  },
  contentBehind: { opacity: 0 },
  contentExpanded: { opacity: 1 },
  header: {
    gap: spacing.xs,
    alignItems: 'center',
    display: 'flex',
    width: '100%',
  },
  controls: {
    gap: spacing.xxs,
    display: 'flex',
    flexShrink: 0,
  },
  title: {
    margin: 0,
    color: textColors['text-default'],
    flexGrow: 1,
    fontSize: fontSizes[2],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.ui,
    minWidth: 0,
  },
  titleMessage: {},
  titleSuccess: { color: textColors['text-success'] },
  titleWarning: { color: textColors['text-warning'] },
  titleError: { color: textColors['text-danger'] },
  titleLoading: {},
  description: {
    margin: 0,
    color: textColors['text-muted'],
    fontSize: fontSizes[1],
    fontWeight: fontWeights.regular,
    lineHeight: lineHeights.compact,
  },
  action: {
    borderRadius: borderRadii.xs,
    borderWidth: 0,
    paddingInline: spacing.s,
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: {
      default: backgroundColors['bg-subtle'],
      ':hover': backgroundColors['bg-hover'],
      ':active': backgroundColors['bg-pressed'],
    },
    color: textColors['text-default'],
    cursor: 'pointer',
    display: 'flex',
    flexShrink: 0,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes[1],
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.compact,
    outlineColor: borderColors['outline'],
    outlineOffset: 1,
    outlineStyle: 'solid',
    outlineWidth: { default: 0, ':focus-visible': spatial['focus-ring-width'] },
    height: spatial['control-height-s'],
  },
  closeIcon: { display: 'block', height: spatial['icon-size-s'], width: spatial['icon-size-s'] },
})
